// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateCreateData, ActivateCreateResponses, AdminCampaignsCreateData, AdminCampaignsCreateResponses, AdminCampaignsDestroyData, AdminCampaignsDestroyResponses, AdminCampaignsListData, AdminCampaignsListResponses, AdminCampaignsPartialUpdateData, AdminCampaignsPartialUpdateResponses, AdminCampaignsRetrieveData, AdminCampaignsRetrieveResponses, AdminCampaignsUpdateData, AdminCampaignsUpdateResponses, AdminCompanyPartialUpdateData, AdminCompanyPartialUpdateResponses, AdminCompanyRetrieveData, AdminCompanyRetrieveResponses, AdminCompanyUpdateData, AdminCompanyUpdateResponses, AdminCurrenciesListData, AdminCurrenciesListResponses, AdminCurrenciesRetrieveData, AdminCurrenciesRetrieveResponses, AdminRewardsCreateData, AdminRewardsCreateResponses, AdminRewardsListData, AdminRewardsListResponses, AdminRewardsPartialUpdateData, AdminRewardsPartialUpdateResponses, AdminRewardsRetrieveData, AdminRewardsRetrieveResponses, AdminRewardsUpdateData, AdminRewardsUpdateResponses, AdminUsersListData, AdminUsersListResponses, AdminUsersRetrieveData, AdminUsersRetrieveResponses, AdminWebhookCreateData, AdminWebhookCreateResponses, DeactivateCreateData, DeactivateCreateResponses, UserCampaignsListData, UserCampaignsListResponses, UserCampaignsRetrieveData, UserCampaignsRetrieveResponses, UserPartialUpdateData, UserPartialUpdateResponses, UserRetrieveData, UserRetrieveResponses, UserRewardsCreateData, UserRewardsCreateResponses, UserRewardsListData, UserRewardsListResponses, UserRewardsRetrieveData, UserRewardsRetrieveResponses, UserUpdateData, UserUpdateResponses, WebhookCreateData, WebhookCreateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Activate service
 */
export const activateCreate = <ThrowOnError extends boolean = false>(options: Options<ActivateCreateData, ThrowOnError>) => (options.client ?? client).post<ActivateCreateResponses, unknown, ThrowOnError>({
    url: '/activate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List campaign
 */
export const adminCampaignsList = <ThrowOnError extends boolean = false>(options?: Options<AdminCampaignsListData, ThrowOnError>) => (options?.client ?? client).get<AdminCampaignsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/',
    ...options
});

/**
 * Create campaign
 */
export const adminCampaignsCreate = <ThrowOnError extends boolean = false>(options: Options<AdminCampaignsCreateData, ThrowOnError>) => (options.client ?? client).post<AdminCampaignsCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete campaign
 */
export const adminCampaignsDestroy = <ThrowOnError extends boolean = false>(options: Options<AdminCampaignsDestroyData, ThrowOnError>) => (options.client ?? client).delete<AdminCampaignsDestroyResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/{id}/',
    ...options
});

/**
 * Retrieve campaign
 */
export const adminCampaignsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminCampaignsRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminCampaignsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/{id}/',
    ...options
});

/**
 * Partially update campaign
 */
export const adminCampaignsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminCampaignsPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<AdminCampaignsPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update campaign
 */
export const adminCampaignsUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminCampaignsUpdateData, ThrowOnError>) => (options.client ?? client).put<AdminCampaignsUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/campaigns/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve company
 */
export const adminCompanyRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyRetrieveData, ThrowOnError>) => (options?.client ?? client).get<AdminCompanyRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options
});

/**
 * Partially update company
 */
export const adminCompanyPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyPartialUpdateData, ThrowOnError>) => (options?.client ?? client).patch<AdminCompanyPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Update company
 */
export const adminCompanyUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyUpdateData, ThrowOnError>) => (options?.client ?? client).put<AdminCompanyUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List currencies
 */
export const adminCurrenciesList = <ThrowOnError extends boolean = false>(options?: Options<AdminCurrenciesListData, ThrowOnError>) => (options?.client ?? client).get<AdminCurrenciesListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/',
    ...options
});

/**
 * Retrieve currency
 */
export const adminCurrenciesRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminCurrenciesRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminCurrenciesRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/{code}/',
    ...options
});

/**
 * List rewards
 */
export const adminRewardsList = <ThrowOnError extends boolean = false>(options?: Options<AdminRewardsListData, ThrowOnError>) => (options?.client ?? client).get<AdminRewardsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/rewards/',
    ...options
});

/**
 * Create reward
 */
export const adminRewardsCreate = <ThrowOnError extends boolean = false>(options: Options<AdminRewardsCreateData, ThrowOnError>) => (options.client ?? client).post<AdminRewardsCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/rewards/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve reward
 */
export const adminRewardsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminRewardsRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminRewardsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/rewards/{id}/',
    ...options
});

/**
 * Partially update reward
 */
export const adminRewardsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminRewardsPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<AdminRewardsPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/rewards/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update reward
 */
export const adminRewardsUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminRewardsUpdateData, ThrowOnError>) => (options.client ?? client).put<AdminRewardsUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/rewards/{id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 */
export const adminUsersList = <ThrowOnError extends boolean = false>(options?: Options<AdminUsersListData, ThrowOnError>) => (options?.client ?? client).get<AdminUsersListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/users/',
    ...options
});

/**
 * Retrieve user
 */
export const adminUsersRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminUsersRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminUsersRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/users/{id}/',
    ...options
});

/**
 * Receive Platform webhook
 */
export const adminWebhookCreate = <ThrowOnError extends boolean = false>(options: Options<AdminWebhookCreateData, ThrowOnError>) => (options.client ?? client).post<AdminWebhookCreateResponses, unknown, ThrowOnError>({
    url: '/admin/webhook/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deactivate service
 */
export const deactivateCreate = <ThrowOnError extends boolean = false>(options: Options<DeactivateCreateData, ThrowOnError>) => (options.client ?? client).post<DeactivateCreateResponses, unknown, ThrowOnError>({
    url: '/deactivate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve user
 */
export const userRetrieve = <ThrowOnError extends boolean = false>(options?: Options<UserRetrieveData, ThrowOnError>) => (options?.client ?? client).get<UserRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options
});

/**
 * Partially update user
 */
export const userPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<UserPartialUpdateData, ThrowOnError>) => (options?.client ?? client).patch<UserPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Update user
 */
export const userUpdate = <ThrowOnError extends boolean = false>(options: Options<UserUpdateData, ThrowOnError>) => (options.client ?? client).put<UserUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List campaigns
 */
export const userCampaignsList = <ThrowOnError extends boolean = false>(options?: Options<UserCampaignsListData, ThrowOnError>) => (options?.client ?? client).get<UserCampaignsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/campaigns/',
    ...options
});

/**
 * Retrieve campaign
 */
export const userCampaignsRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserCampaignsRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserCampaignsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/campaigns/{id}/',
    ...options
});

/**
 * List rewards
 */
export const userRewardsList = <ThrowOnError extends boolean = false>(options?: Options<UserRewardsListData, ThrowOnError>) => (options?.client ?? client).get<UserRewardsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/rewards/',
    ...options
});

/**
 * Create reward
 */
export const userRewardsCreate = <ThrowOnError extends boolean = false>(options: Options<UserRewardsCreateData, ThrowOnError>) => (options.client ?? client).post<UserRewardsCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/rewards/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve user
 */
export const userRewardsRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserRewardsRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserRewardsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/rewards/{id}/',
    ...options
});

/**
 * Receive Platform webhook
 */
export const webhookCreate = <ThrowOnError extends boolean = false>(options: Options<WebhookCreateData, ThrowOnError>) => (options.client ?? client).post<WebhookCreateResponses, unknown, ThrowOnError>({
    url: '/webhook/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
