// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://reward.services.rehive.io/api/' | (string & {});
};

/**
 * This serializer can be used if only a `status` is required in the response.
 */
export type ActionResponse = {
    status?: string;
};

export type Activate = {
    token: string;
    readonly id: string;
    readonly name: string;
    readonly secret: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCampaign = {
    readonly id: string;
    name?: string;
    image?: string | null;
    description?: string;
    start_date: number;
    end_date: number;
    currency: Currency;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account: string;
    readonly total: number;
    readonly fixed_amount: number | null;
    percentage?: string | null;
    readonly balance: number;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency: Currency;
    min_num_transactions?: number | null;
    readonly min_value_transactions: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

export type AdminCampaignResponse = {
    status?: string;
    data?: AdminCampaign;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompany = {
    readonly id: string;
    readonly identifier: string;
    readonly secret: string;
    readonly name: string;
    operational_account?: string | null;
};

export type AdminCompanyResponse = {
    status?: string;
    data?: AdminCompany;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateReward = {
    readonly id: string;
    user: string;
    campaign?: string;
    currency?: string;
    amount?: number;
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
    readonly collection: string | null;
    readonly created: number;
    data?: {
        [key: string]: unknown;
    };
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateUpdateCampaign = {
    readonly id: string;
    name?: string;
    image?: string | null;
    description?: string;
    start_date?: number | null;
    end_date?: number | null;
    currency: string;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account?: string | null;
    total: number;
    fixed_amount?: number;
    percentage?: number | null;
    readonly balance: number;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency?: string | null;
    min_num_transactions?: number | null;
    min_value_transactions?: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminReward = {
    readonly id: string;
    readonly user: string;
    campaign: Campaign;
    currency: Currency;
    readonly amount: number;
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
    readonly collection: string | null;
    readonly type: string;
    readonly created: number;
};

export type AdminRewardResponse = {
    status?: string;
    data?: AdminReward;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminUser = {
    readonly id: string;
    readonly referral_code: string | null;
    readonly referee_code: string | null;
};

export type AdminUserResponse = {
    status?: string;
    data?: AdminUser;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Campaign = {
    readonly id: string;
    name?: string;
    description?: string;
    active?: boolean;
    default_status: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Currency = {
    code: string;
    display_code?: string | null;
    description?: string | null;
    symbol?: string | null;
    unit?: string | null;
    divisibility?: number;
    enabled?: boolean;
};

export type CurrencyResponse = {
    status?: string;
    data?: Currency;
};

export type Deactivate = {
    token: string;
    purge?: boolean;
};

export type PaginatedAdminCampaignList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminCampaign>;
};

export type PaginatedAdminCampaignListResponse = {
    status?: string;
    data?: PaginatedAdminCampaignList;
};

export type PaginatedAdminRewardList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminReward>;
};

export type PaginatedAdminRewardListResponse = {
    status?: string;
    data?: PaginatedAdminRewardList;
};

export type PaginatedAdminUserList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminUser>;
};

export type PaginatedAdminUserListResponse = {
    status?: string;
    data?: PaginatedAdminUserList;
};

export type PaginatedCurrencyList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Currency>;
};

export type PaginatedCurrencyListResponse = {
    status?: string;
    data?: PaginatedCurrencyList;
};

export type PaginatedUserCampaignList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserCampaign>;
};

export type PaginatedUserCampaignListResponse = {
    status?: string;
    data?: PaginatedUserCampaignList;
};

export type PaginatedUserRewardList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserReward>;
};

export type PaginatedUserRewardListResponse = {
    status?: string;
    data?: PaginatedUserRewardList;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompany = {
    readonly id?: string;
    readonly identifier?: string;
    readonly secret?: string;
    readonly name?: string;
    operational_account?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCreateUpdateCampaign = {
    readonly id?: string;
    name?: string;
    image?: string | null;
    description?: string;
    start_date?: number | null;
    end_date?: number | null;
    currency?: string;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account?: string | null;
    total?: number;
    fixed_amount?: number;
    percentage?: number | null;
    readonly balance?: number;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency?: string | null;
    min_num_transactions?: number | null;
    min_value_transactions?: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminReward = {
    readonly id?: string;
    readonly user?: string;
    campaign?: Campaign;
    currency?: Currency;
    readonly amount?: number;
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
    readonly collection?: string | null;
    readonly type?: string;
    readonly created?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUserUpdateReferral = {
    readonly referral_code?: string | null;
    referee_code?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type User = {
    readonly id: string;
    readonly referral_code: string | null;
    readonly referee_code: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserCampaign = {
    readonly id: string;
    name?: string;
    readonly description: string;
    image?: string | null;
    start_date: number;
    end_date: number;
    currency: Currency;
    readonly total: number;
    readonly fixed_amount: number;
    percentage?: string | null;
    readonly balance: number;
    type: string;
    default_status: string;
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    timeframe?: string;
    transactions_currency: Currency;
    min_num_transactions?: number | null;
    readonly min_value_transactions: number | null;
    active?: boolean;
    claim?: boolean;
};

export type UserCampaignResponse = {
    status?: string;
    data?: UserCampaign;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserCreateReward = {
    readonly id: string;
    readonly user: string;
    campaign: string;
    currency: Currency;
    readonly amount: number;
    readonly status: string;
    readonly collection: string | null;
    readonly created: number;
};

export type UserResponse = {
    status?: string;
    data?: User;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserReward = {
    readonly id: string;
    readonly user: string;
    campaign: Campaign;
    currency: Currency;
    readonly amount: number;
    readonly status: string;
    readonly type: string;
    collection?: string | null;
    readonly created: number;
};

export type UserRewardResponse = {
    status?: string;
    data?: UserReward;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserUpdateReferral = {
    readonly referral_code: string | null;
    referee_code: string;
};

export type Webhook = {
    id: string;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify';
    company: string;
    data: {
        [key: string]: unknown;
    };
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCampaignWritable = {
    name?: string;
    image?: string | null;
    description?: string;
    start_date: number;
    end_date: number;
    currency: Currency;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account: string;
    percentage?: string | null;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency: Currency;
    min_num_transactions?: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

export type AdminCampaignResponseWritable = {
    status?: string;
    data?: AdminCampaignWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompanyWritable = {
    operational_account?: string | null;
};

export type AdminCompanyResponseWritable = {
    status?: string;
    data?: AdminCompanyWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateRewardWritable = {
    user: string;
    campaign?: string;
    currency?: string;
    amount?: number;
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
    data?: {
        [key: string]: unknown;
    };
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateUpdateCampaignWritable = {
    name?: string;
    image?: string | null;
    description?: string;
    start_date?: number | null;
    end_date?: number | null;
    currency: string;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account?: string | null;
    total: number;
    fixed_amount?: number;
    percentage?: number | null;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency?: string | null;
    min_num_transactions?: number | null;
    min_value_transactions?: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminRewardWritable = {
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
};

export type AdminRewardResponseWritable = {
    status?: string;
    data?: AdminRewardWritable;
};

export type AdminUserResponseWritable = {
    status?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type CampaignWritable = {
    name?: string;
    description?: string;
    active?: boolean;
    default_status: string;
};

export type PaginatedAdminCampaignListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminCampaignWritable>;
};

export type PaginatedAdminCampaignListResponseWritable = {
    status?: string;
    data?: PaginatedAdminCampaignListWritable;
};

export type PaginatedAdminRewardListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminRewardWritable>;
};

export type PaginatedAdminRewardListResponseWritable = {
    status?: string;
    data?: PaginatedAdminRewardListWritable;
};

export type PaginatedAdminUserListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<unknown>;
};

export type PaginatedAdminUserListResponseWritable = {
    status?: string;
    data?: PaginatedAdminUserListWritable;
};

export type PaginatedUserCampaignListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserCampaignWritable>;
};

export type PaginatedUserCampaignListResponseWritable = {
    status?: string;
    data?: PaginatedUserCampaignListWritable;
};

export type PaginatedUserRewardListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserRewardWritable>;
};

export type PaginatedUserRewardListResponseWritable = {
    status?: string;
    data?: PaginatedUserRewardListWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompanyWritable = {
    operational_account?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCreateUpdateCampaignWritable = {
    name?: string;
    image?: string | null;
    description?: string;
    start_date?: number | null;
    end_date?: number | null;
    currency?: string;
    credit_account_name?: string | null;
    credit_account?: string | null;
    account?: string | null;
    total?: number;
    fixed_amount?: number;
    percentage?: number | null;
    /**
     * * `percentage` - Percentage
     * * `fixed` - Fixed
     * * `fixedpercentage` - Fixedpercentage
     */
    type?: 'percentage' | 'fixed' | 'fixedpercentage';
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    default_status?: 'pending' | 'accepted' | 'rejected';
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    /**
     * * `daily` - Daily
     * * `weekly` - Weekly
     * * `monthly` - Monthly
     */
    timeframe?: 'daily' | 'weekly' | 'monthly' | '' | null;
    transactions_currency?: string | null;
    min_num_transactions?: number | null;
    min_value_transactions?: number | null;
    active?: boolean;
    visible?: boolean;
    claim?: boolean;
    expression?: string | null;
    /**
     * * `company.link.create` - company.link.create
     * * `company.link.update` - company.link.update
     * * `company.update` - company.update
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     * * `user.create` - user.create
     * * `user.update` - user.update
     * * `user.password.reset` - user.password.reset
     * * `user.password.set` - user.password.set
     * * `user.deactivate.verify` - user.deactivate.verify
     * * `user.request_delete.verify` - user.request_delete.verify
     * * `user.email.verify` - user.email.verify
     * * `user.mobile.verify` - user.mobile.verify
     * * `email.create` - email.create
     * * `email.update` - email.update
     * * `mobile.create` - mobile.create
     * * `mobile.update` - mobile.update
     * * `address.create` - address.create
     * * `address.update` - address.update
     * * `document.create` - document.create
     * * `document.update` - document.update
     * * `bank_account.create` - bank_account.create
     * * `bank_account.update` - bank_account.update
     * * `crypto_account.create` - crypto_account.create
     * * `crypto_account.update` - crypto_account.update
     * * `account.create` - account.create
     * * `account.update` - account.update
     * * `transaction.create` - transaction.create
     * * `transaction.update` - transaction.update
     * * `transaction.initiate` - transaction.initiate
     * * `transaction.execute` - transaction.execute
     * * `transaction.transition.create` - transaction.transition.create
     * * `transaction.transition.update` - transaction.transition.update
     * * `mfa.sms.verify` - mfa.sms.verify
     */
    event?: 'company.link.create' | 'company.link.update' | 'company.update' | 'currency.create' | 'currency.update' | 'user.create' | 'user.update' | 'user.password.reset' | 'user.password.set' | 'user.deactivate.verify' | 'user.request_delete.verify' | 'user.email.verify' | 'user.mobile.verify' | 'email.create' | 'email.update' | 'mobile.create' | 'mobile.update' | 'address.create' | 'address.update' | 'document.create' | 'document.update' | 'bank_account.create' | 'bank_account.update' | 'crypto_account.create' | 'crypto_account.update' | 'account.create' | 'account.update' | 'transaction.create' | 'transaction.update' | 'transaction.initiate' | 'transaction.execute' | 'transaction.transition.create' | 'transaction.transition.update' | 'mfa.sms.verify' | '' | null;
    event_user?: string | null;
    event_amount?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminRewardWritable = {
    /**
     * * `pending` - Pending
     * * `accepted` - Accepted
     * * `rejected` - Rejected
     */
    status?: 'pending' | 'accepted' | 'rejected';
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUserUpdateReferralWritable = {
    referee_code?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserCampaignWritable = {
    name?: string;
    image?: string | null;
    start_date: number;
    end_date: number;
    currency: Currency;
    percentage?: string | null;
    type: string;
    default_status: string;
    users?: Array<unknown>;
    groups?: Array<unknown>;
    max_per_user?: number | null;
    max_per_user_per_timeframe?: number | null;
    timeframe?: string;
    transactions_currency: Currency;
    min_num_transactions?: number | null;
    active?: boolean;
    claim?: boolean;
};

export type UserCampaignResponseWritable = {
    status?: string;
    data?: UserCampaignWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserCreateRewardWritable = {
    campaign: string;
    data?: {
        [key: string]: unknown;
    };
};

export type UserResponseWritable = {
    status?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserRewardWritable = {
    collection?: string | null;
};

export type UserRewardResponseWritable = {
    status?: string;
    data?: UserRewardWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserUpdateReferralWritable = {
    referee_code: string;
};

export type ActivateCreateData = {
    body: Activate;
    path?: never;
    query?: never;
    url: '/activate/';
};

export type ActivateCreateResponses = {
    200: ActionResponse;
};

export type ActivateCreateResponse = ActivateCreateResponses[keyof ActivateCreateResponses];

export type AdminCampaignsListData = {
    body?: never;
    path?: never;
    query?: {
        active?: boolean;
        available?: string;
        currency?: string;
        end_date?: string;
        end_date__gt?: string;
        end_date__lt?: string;
        id?: string;
        name__contains?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        search?: string;
        start_date?: string;
        start_date__gt?: string;
        start_date__lt?: string;
        type?: string;
        visible?: boolean;
    };
    url: '/admin/campaigns/';
};

export type AdminCampaignsListResponses = {
    200: PaginatedAdminCampaignListResponse;
};

export type AdminCampaignsListResponse = AdminCampaignsListResponses[keyof AdminCampaignsListResponses];

export type AdminCampaignsCreateData = {
    body: AdminCreateUpdateCampaignWritable;
    path?: never;
    query?: never;
    url: '/admin/campaigns/';
};

export type AdminCampaignsCreateResponses = {
    201: AdminCampaignResponse;
};

export type AdminCampaignsCreateResponse = AdminCampaignsCreateResponses[keyof AdminCampaignsCreateResponses];

export type AdminCampaignsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/campaigns/{id}/';
};

export type AdminCampaignsDestroyResponses = {
    200: AdminCampaignResponse;
};

export type AdminCampaignsDestroyResponse = AdminCampaignsDestroyResponses[keyof AdminCampaignsDestroyResponses];

export type AdminCampaignsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/campaigns/{id}/';
};

export type AdminCampaignsRetrieveResponses = {
    200: AdminCampaignResponse;
};

export type AdminCampaignsRetrieveResponse = AdminCampaignsRetrieveResponses[keyof AdminCampaignsRetrieveResponses];

export type AdminCampaignsPartialUpdateData = {
    body?: PatchedAdminCreateUpdateCampaignWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/campaigns/{id}/';
};

export type AdminCampaignsPartialUpdateResponses = {
    200: AdminCampaignResponse;
};

export type AdminCampaignsPartialUpdateResponse = AdminCampaignsPartialUpdateResponses[keyof AdminCampaignsPartialUpdateResponses];

export type AdminCampaignsUpdateData = {
    body: AdminCreateUpdateCampaignWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/campaigns/{id}/';
};

export type AdminCampaignsUpdateResponses = {
    200: AdminCampaignResponse;
};

export type AdminCampaignsUpdateResponse = AdminCampaignsUpdateResponses[keyof AdminCampaignsUpdateResponses];

export type AdminCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyRetrieveResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyRetrieveResponse = AdminCompanyRetrieveResponses[keyof AdminCompanyRetrieveResponses];

export type AdminCompanyPartialUpdateData = {
    body?: PatchedAdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyPartialUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyPartialUpdateResponse = AdminCompanyPartialUpdateResponses[keyof AdminCompanyPartialUpdateResponses];

export type AdminCompanyUpdateData = {
    body?: AdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyUpdateResponse = AdminCompanyUpdateResponses[keyof AdminCompanyUpdateResponses];

export type AdminCurrenciesListData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/currencies/';
};

export type AdminCurrenciesListResponses = {
    200: PaginatedCurrencyListResponse;
};

export type AdminCurrenciesListResponse = AdminCurrenciesListResponses[keyof AdminCurrenciesListResponses];

export type AdminCurrenciesRetrieveData = {
    body?: never;
    path: {
        code: string;
    };
    query?: never;
    url: '/admin/currencies/{code}/';
};

export type AdminCurrenciesRetrieveResponses = {
    200: CurrencyResponse;
};

export type AdminCurrenciesRetrieveResponse = AdminCurrenciesRetrieveResponses[keyof AdminCurrenciesRetrieveResponses];

export type AdminRewardsListData = {
    body?: never;
    path?: never;
    query?: {
        campaign?: string;
        currency?: string;
        id?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        status?: string;
        status__in?: string;
        type?: string;
        user?: string;
    };
    url: '/admin/rewards/';
};

export type AdminRewardsListResponses = {
    200: PaginatedAdminRewardListResponse;
};

export type AdminRewardsListResponse = AdminRewardsListResponses[keyof AdminRewardsListResponses];

export type AdminRewardsCreateData = {
    body: AdminCreateRewardWritable;
    path?: never;
    query?: never;
    url: '/admin/rewards/';
};

export type AdminRewardsCreateResponses = {
    201: AdminRewardResponse;
};

export type AdminRewardsCreateResponse = AdminRewardsCreateResponses[keyof AdminRewardsCreateResponses];

export type AdminRewardsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/rewards/{id}/';
};

export type AdminRewardsRetrieveResponses = {
    200: AdminRewardResponse;
};

export type AdminRewardsRetrieveResponse = AdminRewardsRetrieveResponses[keyof AdminRewardsRetrieveResponses];

export type AdminRewardsPartialUpdateData = {
    body?: PatchedAdminRewardWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/rewards/{id}/';
};

export type AdminRewardsPartialUpdateResponses = {
    200: AdminRewardResponse;
};

export type AdminRewardsPartialUpdateResponse = AdminRewardsPartialUpdateResponses[keyof AdminRewardsPartialUpdateResponses];

export type AdminRewardsUpdateData = {
    body?: AdminRewardWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/rewards/{id}/';
};

export type AdminRewardsUpdateResponses = {
    200: AdminRewardResponse;
};

export type AdminRewardsUpdateResponse = AdminRewardsUpdateResponses[keyof AdminRewardsUpdateResponses];

export type AdminUsersListData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        referee_code?: string;
        referral_code?: string;
    };
    url: '/admin/users/';
};

export type AdminUsersListResponses = {
    200: PaginatedAdminUserListResponse;
};

export type AdminUsersListResponse = AdminUsersListResponses[keyof AdminUsersListResponses];

export type AdminUsersRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/';
};

export type AdminUsersRetrieveResponses = {
    200: AdminUserResponse;
};

export type AdminUsersRetrieveResponse = AdminUsersRetrieveResponses[keyof AdminUsersRetrieveResponses];

export type AdminWebhookCreateData = {
    body: Webhook;
    path?: never;
    query?: never;
    url: '/admin/webhook/';
};

export type AdminWebhookCreateResponses = {
    200: ActionResponse;
};

export type AdminWebhookCreateResponse = AdminWebhookCreateResponses[keyof AdminWebhookCreateResponses];

export type DeactivateCreateData = {
    body: Deactivate;
    path?: never;
    query?: never;
    url: '/deactivate/';
};

export type DeactivateCreateResponses = {
    200: ActionResponse;
};

export type DeactivateCreateResponse = DeactivateCreateResponses[keyof DeactivateCreateResponses];

export type UserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserRetrieveResponses = {
    200: UserResponse;
};

export type UserRetrieveResponse = UserRetrieveResponses[keyof UserRetrieveResponses];

export type UserPartialUpdateData = {
    body?: PatchedUserUpdateReferralWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserPartialUpdateResponses = {
    200: UserResponse;
};

export type UserPartialUpdateResponse = UserPartialUpdateResponses[keyof UserPartialUpdateResponses];

export type UserUpdateData = {
    body: UserUpdateReferralWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserUpdateResponses = {
    200: UserResponse;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];

export type UserCampaignsListData = {
    body?: never;
    path?: never;
    query?: {
        active?: boolean;
        available?: string;
        currency?: string;
        end_date?: string;
        end_date__gt?: string;
        end_date__lt?: string;
        id?: string;
        name__contains?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        search?: string;
        start_date?: string;
        start_date__gt?: string;
        start_date__lt?: string;
        type?: string;
        visible?: boolean;
    };
    url: '/user/campaigns/';
};

export type UserCampaignsListResponses = {
    200: PaginatedUserCampaignListResponse;
};

export type UserCampaignsListResponse = UserCampaignsListResponses[keyof UserCampaignsListResponses];

export type UserCampaignsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/campaigns/{id}/';
};

export type UserCampaignsRetrieveResponses = {
    200: UserCampaignResponse;
};

export type UserCampaignsRetrieveResponse = UserCampaignsRetrieveResponses[keyof UserCampaignsRetrieveResponses];

export type UserRewardsListData = {
    body?: never;
    path?: never;
    query?: {
        campaign?: string;
        currency?: string;
        id?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        status?: string;
        status__in?: string;
        type?: string;
    };
    url: '/user/rewards/';
};

export type UserRewardsListResponses = {
    200: PaginatedUserRewardListResponse;
};

export type UserRewardsListResponse = UserRewardsListResponses[keyof UserRewardsListResponses];

export type UserRewardsCreateData = {
    body: UserCreateRewardWritable;
    path?: never;
    query?: never;
    url: '/user/rewards/';
};

export type UserRewardsCreateResponses = {
    201: UserRewardResponse;
};

export type UserRewardsCreateResponse = UserRewardsCreateResponses[keyof UserRewardsCreateResponses];

export type UserRewardsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/rewards/{id}/';
};

export type UserRewardsRetrieveResponses = {
    200: UserRewardResponse;
};

export type UserRewardsRetrieveResponse = UserRewardsRetrieveResponses[keyof UserRewardsRetrieveResponses];

export type WebhookCreateData = {
    body: Webhook;
    path?: never;
    query?: never;
    url: '/webhook/';
};

export type WebhookCreateResponses = {
    200: ActionResponse;
};

export type WebhookCreateResponse = WebhookCreateResponses[keyof WebhookCreateResponses];
