// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateCreateData, ActivateCreateResponses, AdminAddressesListData, AdminAddressesListResponses, AdminAddressesRetrieveData, AdminAddressesRetrieveResponses, AdminCompanyPartialUpdateData, AdminCompanyPartialUpdateResponses, AdminCompanyRetrieveData, AdminCompanyRetrieveResponses, AdminCompanyUpdateData, AdminCompanyUpdateResponses, AdminOnchainTransactionsListData, AdminOnchainTransactionsListResponses, AdminOnchainTransactionsRetrieveData, AdminOnchainTransactionsRetrieveResponses, AlchemyWebhookCreateData, AlchemyWebhookCreateResponses, DeactivateCreateData, DeactivateCreateResponses, UserAccountAddressLookupCreateData, UserAccountAddressLookupCreateResponses, UserAddressesCreateData, UserAddressesCreateResponses, UserAddressesListData, UserAddressesListResponses, UserAddressesRetrieveData, UserAddressesRetrieveResponses, UserOnchainTransactionsCancelCreateData, UserOnchainTransactionsCancelCreateResponses, UserOnchainTransactionsListData, UserOnchainTransactionsListResponses, UserOnchainTransactionsPartialUpdateData, UserOnchainTransactionsPartialUpdateResponses, UserOnchainTransactionsRetrieveData, UserOnchainTransactionsRetrieveResponses, UserOnchainTransactionsUpdateData, UserOnchainTransactionsUpdateResponses, WebhookCreateData, WebhookCreateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const activateCreate = <ThrowOnError extends boolean = false>(options: Options<ActivateCreateData, ThrowOnError>) => (options.client ?? client).post<ActivateCreateResponses, unknown, ThrowOnError>({
    url: '/activate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const adminAddressesList = <ThrowOnError extends boolean = false>(options?: Options<AdminAddressesListData, ThrowOnError>) => (options?.client ?? client).get<AdminAddressesListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/addresses/',
    ...options
});

export const adminAddressesRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminAddressesRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminAddressesRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/addresses/{identifier}/',
    ...options
});

export const adminCompanyRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyRetrieveData, ThrowOnError>) => (options?.client ?? client).get<AdminCompanyRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options
});

export const adminCompanyPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyPartialUpdateData, ThrowOnError>) => (options?.client ?? client).patch<AdminCompanyPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const adminCompanyUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyUpdateData, ThrowOnError>) => (options?.client ?? client).put<AdminCompanyUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const adminOnchainTransactionsList = <ThrowOnError extends boolean = false>(options?: Options<AdminOnchainTransactionsListData, ThrowOnError>) => (options?.client ?? client).get<AdminOnchainTransactionsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/onchain-transactions/',
    ...options
});

export const adminOnchainTransactionsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminOnchainTransactionsRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminOnchainTransactionsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/onchain-transactions/{identifier}/',
    ...options
});

export const alchemyWebhookCreate = <ThrowOnError extends boolean = false>(options: Options<AlchemyWebhookCreateData, ThrowOnError>) => (options.client ?? client).post<AlchemyWebhookCreateResponses, unknown, ThrowOnError>({
    url: '/alchemy_webhook/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deactivateCreate = <ThrowOnError extends boolean = false>(options: Options<DeactivateCreateData, ThrowOnError>) => (options.client ?? client).post<DeactivateCreateResponses, unknown, ThrowOnError>({
    url: '/deactivate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userAccountAddressLookupCreate = <ThrowOnError extends boolean = false>(options: Options<UserAccountAddressLookupCreateData, ThrowOnError>) => (options.client ?? client).post<UserAccountAddressLookupCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/account-address-lookup/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userAddressesList = <ThrowOnError extends boolean = false>(options?: Options<UserAddressesListData, ThrowOnError>) => (options?.client ?? client).get<UserAddressesListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/addresses/',
    ...options
});

export const userAddressesCreate = <ThrowOnError extends boolean = false>(options: Options<UserAddressesCreateData, ThrowOnError>) => (options.client ?? client).post<UserAddressesCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/addresses/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userAddressesRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserAddressesRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserAddressesRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/addresses/{identifier}/',
    ...options
});

export const userOnchainTransactionsList = <ThrowOnError extends boolean = false>(options?: Options<UserOnchainTransactionsListData, ThrowOnError>) => (options?.client ?? client).get<UserOnchainTransactionsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/onchain-transactions/',
    ...options
});

export const userOnchainTransactionsRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserOnchainTransactionsRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserOnchainTransactionsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/onchain-transactions/{identifier}/',
    ...options
});

export const userOnchainTransactionsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UserOnchainTransactionsPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<UserOnchainTransactionsPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/onchain-transactions/{identifier}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userOnchainTransactionsUpdate = <ThrowOnError extends boolean = false>(options: Options<UserOnchainTransactionsUpdateData, ThrowOnError>) => (options.client ?? client).put<UserOnchainTransactionsUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/onchain-transactions/{identifier}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userOnchainTransactionsCancelCreate = <ThrowOnError extends boolean = false>(options: Options<UserOnchainTransactionsCancelCreateData, ThrowOnError>) => (options.client ?? client).post<UserOnchainTransactionsCancelCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/onchain-transactions/{identifier}/cancel/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const webhookCreate = <ThrowOnError extends boolean = false>(options: Options<WebhookCreateData, ThrowOnError>) => (options.client ?? client).post<WebhookCreateResponses, unknown, ThrowOnError>({
    url: '/webhook/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
