// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://alchemy.services.rehive.com/api/' | (string & {});
};

/**
 * Serializer for looking up a crypto address from a Rehive account reference.
 * Accepts an account reference and chain, resolves the account_currency UUID
 * via Rehive, then calls the Bridge extension to get a liquidation address.
 */
export type AccountAddressLookup = {
    account: string;
    currency_code: string;
    chain: string;
    readonly address: string;
};

export type AccountAddressLookupResponse = {
    status?: string;
    data?: AccountAddressLookup;
};

/**
 * This serializer can be used if only a `status` is required in the response.
 */
export type ActionResponse = {
    status?: string;
};

/**
 * Serialize the activation data, should be a token that represents an admin
 * user.
 */
export type Activate = {
    token: string;
    readonly id: string;
    readonly name: string;
    readonly secret: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Address = {
    readonly identifier: string;
    address: string;
    user: User;
    rehive_account: string;
    readonly parent_address: string;
    readonly subtype: string;
    readonly provider: string;
    readonly created: number;
    readonly updated: number;
};

export type AddressResponse = {
    status?: string;
    data?: Address;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminAddress = {
    readonly id: string;
    readonly address: string;
    readonly rehive_account: string;
    user: User;
    readonly parent_address: string;
    readonly created: number;
    readonly updated: number;
};

export type AdminAddressResponse = {
    status?: string;
    data?: AdminAddress;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompany = {
    readonly id: string;
    readonly secret: string;
    readonly name: string;
    /**
     * * `test` - Test
     * * `production` - Production
     */
    readonly mode: 'test' | 'production';
};

export type AdminCompanyResponse = {
    status?: string;
    data?: AdminCompany;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateAddress = {
    address: string;
    rehive_account: string;
};

/**
 * Input for minting a new deposit address. Resolves the parent Address (by
 * identifier or on-chain address) and the matching CompanyDepositFactory —
 * keyed by either (company, chain, subtype) or (company, chain, provider),
 * exactly one of which must be supplied — computes the CREATE2 address via
 * RPC, creates the Address row, and subscribes it to Alchemy.
 */
export type AdminCreateDepositAddress = {
    parent_address: string;
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    subtype?: string;
    provider?: string;
    readonly id: string;
    readonly address: string;
    readonly deposit_index: number;
    readonly created: number;
};

export type AdminCreateDepositAddressResponse = {
    status?: string;
    data?: AdminCreateDepositAddress;
};

/**
 * Create a CompanyDepositFactory row and (by default) deploy the on-chain
 * factory. Exactly one of `subtype` or `provider` must be supplied — a
 * factory is either bound to a Rehive payment-method subtype (and emits
 * Rehive credits directly on sweep) or to a third-party provider tag (and
 * records ProviderMonitoredDeposit rows for the provider's pending
 * transactions to join against).
 *
 * The operator keypair is pulled from OPERATOR_ADDRESS / OPERATOR_PRIVATE_KEY
 * env vars at create time, copied onto the row, and the private key is
 * Fernet-encrypted under OPERATOR_KEY_MASTER before being written. The
 * plaintext never touches the DB.
 */
export type AdminCreateDepositFactory = {
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    subtype?: string;
    provider?: string;
    deploy?: boolean;
    readonly id: string;
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain_out: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly subtype_out: string;
    readonly provider_out: string;
    readonly factory_address: string;
    readonly implementation_address: string;
    readonly operator_address_out: string;
    readonly active: boolean;
    readonly created: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminDepositFactory = {
    readonly id: string;
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly subtype: string;
    readonly provider: string;
    readonly factory_address: string;
    readonly implementation_address: string;
    readonly operator_address: string;
    readonly active: boolean;
    readonly created: number;
    readonly updated: number;
};

export type AdminDepositFactoryResponse = {
    status?: string;
    data?: AdminDepositFactory;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminOnchainTransaction = {
    readonly id: string;
    readonly hash: string;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    readonly status: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly from_address: string;
    readonly destination_address: string;
    readonly amount: string;
    readonly rehive_transaction_id: string;
    readonly unsigned_transaction_blob: unknown;
    currency: Currency;
    readonly collection: string;
    address: AdminAddress;
    readonly created: number;
    readonly updated: number;
};

export type AdminOnchainTransactionResponse = {
    status?: string;
    data?: AdminOnchainTransaction;
};

export type AlchemyWebhook = {
    event: unknown;
    createdAt: string;
    type: string;
    webhookId: string;
    id: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Currency = {
    readonly code: string;
    /**
     * * `USDC` - Usdc
     * * `ETH` - Eth
     */
    readonly onchain_code: 'USDC' | 'ETH';
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly token_address: string;
    readonly display_code: string;
    readonly description: string;
    readonly symbol: string;
    readonly unit: string;
    readonly divisibility: number;
};

/**
 * Serialize the deactivation data, should be a token that represents an admin
 * user.
 */
export type Deactivate = {
    token: string;
    purge?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type OnchainTransaction = {
    readonly identifier: string;
    hash?: string | null;
    user_op_hash?: string | null;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    status: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly from_address: string;
    readonly destination_address: string;
    readonly amount: string;
    readonly rehive_transaction_id: string;
    readonly unsigned_transaction_blob: unknown;
    currency: Currency;
    readonly collection: string;
    readonly created: number;
    readonly updated: number;
};

export type OnchainTransactionResponse = {
    status?: string;
    data?: OnchainTransaction;
};

export type PaginatedAddressList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Address>;
};

export type PaginatedAddressListResponse = {
    status?: string;
    data?: PaginatedAddressList;
};

export type PaginatedAdminAddressList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdminAddress>;
};

export type PaginatedAdminAddressListResponse = {
    status?: string;
    data?: PaginatedAdminAddressList;
};

export type PaginatedAdminDepositFactoryList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdminDepositFactory>;
};

export type PaginatedAdminDepositFactoryListResponse = {
    status?: string;
    data?: PaginatedAdminDepositFactoryList;
};

export type PaginatedAdminOnchainTransactionList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdminOnchainTransaction>;
};

export type PaginatedAdminOnchainTransactionListResponse = {
    status?: string;
    data?: PaginatedAdminOnchainTransactionList;
};

export type PaginatedOnchainTransactionList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<OnchainTransaction>;
};

export type PaginatedOnchainTransactionListResponse = {
    status?: string;
    data?: PaginatedOnchainTransactionList;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompany = {
    readonly id?: string;
    readonly secret?: string;
    readonly name?: string;
    /**
     * * `test` - Test
     * * `production` - Production
     */
    readonly mode?: 'test' | 'production';
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedOnchainTransaction = {
    readonly identifier?: string;
    hash?: string | null;
    user_op_hash?: string | null;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    status?: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    readonly chain?: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    readonly from_address?: string;
    readonly destination_address?: string;
    readonly amount?: string;
    readonly rehive_transaction_id?: string;
    readonly unsigned_transaction_blob?: unknown;
    currency?: Currency;
    readonly collection?: string;
    readonly created?: number;
    readonly updated?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionCollection = {
    readonly identifier?: string;
    hash?: string;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    readonly status?: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUser = {
    readonly identifier?: string;
    private_key_exported?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionCollection = {
    readonly identifier: string;
    hash: string;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    readonly status: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
};

export type TransactionCollectionResponse = {
    status?: string;
    data?: TransactionCollection;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type User = {
    readonly identifier: string;
    private_key_exported?: number;
};

/**
 * Request body for POST /user/addresses/. Two mutually-exclusive modes, both
 * scoped to the calling user:
 *
 * * Direct registration — {address, rehive_account}
 * * Deposit address      — {parent_address, chain, subtype} OR
 * {parent_address, chain, provider}
 * Mirrors the admin deposit-addresses endpoint: resolves the company's
 * factory by (chain, subtype) or (chain, provider) — exactly one must
 * be supplied — computes the next CREATE2 deposit address, creates the
 * Address row, and subscribes it to Alchemy monitoring.
 * `parent_address` accepts the parent's identifier or on-chain address
 * and must resolve to one of the caller's own Address rows.
 *
 * The response is rendered with AddressSerializer.
 */
export type UserCreateAddress = {
    address?: string;
    rehive_account?: string;
};

export type UserResponse = {
    status?: string;
    data?: User;
};

export type Webhook = {
    id: string;
    /**
     * * `account.currency.create` - Account Currency Create
     * * `bank_account.create` - Bank Account Create
     * * `bank_account.update` - Bank Account Update
     * * `bank_account.delete` - Bank Account Delete
     * * `currency.create` - Currency Create
     * * `currency.update` - Currency Update
     * * `transaction.initiate` - Transaction Initiate
     * * `transaction.update` - Transaction Update
     * * `transaction.transition.update` - Transaction Transition Update
     * * `user.update` - User Update
     */
    event: 'account.currency.create' | 'bank_account.create' | 'bank_account.update' | 'bank_account.delete' | 'currency.create' | 'currency.update' | 'transaction.initiate' | 'transaction.update' | 'transaction.transition.update' | 'user.update';
    company: string;
    data: unknown;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AddressWritable = {
    address: string;
    rehive_account: string;
};

export type AddressResponseWritable = {
    status?: string;
    data?: AddressWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminAddressWritable = {
    [key: string]: unknown;
};

export type AdminAddressResponseWritable = {
    status?: string;
    data?: AdminAddressWritable;
};

export type AdminCompanyResponseWritable = {
    status?: string;
};

export type AdminDepositFactoryResponseWritable = {
    status?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminOnchainTransactionWritable = {
    [key: string]: unknown;
};

export type AdminOnchainTransactionResponseWritable = {
    status?: string;
    data?: AdminOnchainTransactionWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type OnchainTransactionWritable = {
    hash?: string | null;
    user_op_hash?: string | null;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    status: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
};

export type OnchainTransactionResponseWritable = {
    status?: string;
    data?: OnchainTransactionWritable;
};

export type PaginatedAddressListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AddressWritable>;
};

export type PaginatedAddressListResponseWritable = {
    status?: string;
    data?: PaginatedAddressListWritable;
};

export type PaginatedAdminAddressListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdminAddressWritable>;
};

export type PaginatedAdminAddressListResponseWritable = {
    status?: string;
    data?: PaginatedAdminAddressListWritable;
};

export type PaginatedAdminDepositFactoryListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedAdminDepositFactoryListResponseWritable = {
    status?: string;
    data?: PaginatedAdminDepositFactoryListWritable;
};

export type PaginatedAdminOnchainTransactionListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdminOnchainTransactionWritable>;
};

export type PaginatedAdminOnchainTransactionListResponseWritable = {
    status?: string;
    data?: PaginatedAdminOnchainTransactionListWritable;
};

export type PaginatedOnchainTransactionListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<OnchainTransactionWritable>;
};

export type PaginatedOnchainTransactionListResponseWritable = {
    status?: string;
    data?: PaginatedOnchainTransactionListWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedOnchainTransactionWritable = {
    hash?: string | null;
    user_op_hash?: string | null;
    /**
     * * `pending` - Pending
     * * `signed` - Signed
     * * `broadcast` - Broadcast
     * * `confirmed` - Confirmed
     * * `failed` - Failed
     * * `cancelled` - Cancelled
     */
    status?: 'pending' | 'signed' | 'broadcast' | 'confirmed' | 'failed' | 'cancelled';
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionCollectionWritable = {
    hash?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUserWritable = {
    private_key_exported?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionCollectionWritable = {
    hash: string;
};

export type TransactionCollectionResponseWritable = {
    status?: string;
    data?: TransactionCollectionWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserWritable = {
    private_key_exported?: number;
};

/**
 * Request body for POST /user/addresses/. Two mutually-exclusive modes, both
 * scoped to the calling user:
 *
 * * Direct registration — {address, rehive_account}
 * * Deposit address      — {parent_address, chain, subtype} OR
 * {parent_address, chain, provider}
 * Mirrors the admin deposit-addresses endpoint: resolves the company's
 * factory by (chain, subtype) or (chain, provider) — exactly one must
 * be supplied — computes the next CREATE2 deposit address, creates the
 * Address row, and subscribes it to Alchemy monitoring.
 * `parent_address` accepts the parent's identifier or on-chain address
 * and must resolve to one of the caller's own Address rows.
 *
 * The response is rendered with AddressSerializer.
 */
export type UserCreateAddressWritable = {
    address?: string;
    rehive_account?: string;
    parent_address?: string;
    /**
     * * `ETH_SEPOLIA` - Eth Sepolia
     * * `ETH_MAINNET` - Eth Mainnet
     * * `BASE_MAINNET` - Base Mainnet
     * * `BASE_SEPOLIA` - Base Sepolia
     */
    chain?: 'ETH_SEPOLIA' | 'ETH_MAINNET' | 'BASE_MAINNET' | 'BASE_SEPOLIA';
    subtype?: string;
    provider?: string;
};

export type UserResponseWritable = {
    status?: string;
    data?: UserWritable;
};

export type ActivateCreateData = {
    body: Activate;
    path?: never;
    query?: never;
    url: '/activate/';
};

export type ActivateCreateResponses = {
    200: ActionResponse;
};

export type ActivateCreateResponse = ActivateCreateResponses[keyof ActivateCreateResponses];

export type AdminAddressesListData = {
    body?: never;
    path?: never;
    query?: {
        address?: string;
        has_parent?: boolean;
        has_rehive_account?: boolean;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        provider?: string;
        rehive_account?: string;
        subtype?: string;
        user?: string;
    };
    url: '/admin/addresses/';
};

export type AdminAddressesListResponses = {
    200: PaginatedAdminAddressListResponse;
};

export type AdminAddressesListResponse = AdminAddressesListResponses[keyof AdminAddressesListResponses];

export type AdminAddressesCreateData = {
    body: AdminCreateAddress;
    path?: never;
    query?: never;
    url: '/admin/addresses/';
};

export type AdminAddressesCreateResponses = {
    201: AdminAddressResponse;
};

export type AdminAddressesCreateResponse = AdminAddressesCreateResponses[keyof AdminAddressesCreateResponses];

export type AdminAddressesDestroyData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/addresses/{identifier}/';
};

export type AdminAddressesDestroyResponses = {
    200: AdminAddressResponse;
};

export type AdminAddressesDestroyResponse = AdminAddressesDestroyResponses[keyof AdminAddressesDestroyResponses];

export type AdminAddressesRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/addresses/{identifier}/';
};

export type AdminAddressesRetrieveResponses = {
    200: AdminAddressResponse;
};

export type AdminAddressesRetrieveResponse = AdminAddressesRetrieveResponses[keyof AdminAddressesRetrieveResponses];

export type AdminCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyRetrieveResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyRetrieveResponse = AdminCompanyRetrieveResponses[keyof AdminCompanyRetrieveResponses];

export type AdminCompanyPartialUpdateData = {
    body?: PatchedAdminCompany;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyPartialUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyPartialUpdateResponse = AdminCompanyPartialUpdateResponses[keyof AdminCompanyPartialUpdateResponses];

export type AdminCompanyUpdateData = {
    body?: AdminCompany;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyUpdateResponse = AdminCompanyUpdateResponses[keyof AdminCompanyUpdateResponses];

export type AdminDepositAddressesCreateData = {
    body: AdminCreateDepositAddress;
    path?: never;
    query?: never;
    url: '/admin/deposit-addresses/';
};

export type AdminDepositAddressesCreateResponses = {
    201: AdminCreateDepositAddressResponse;
};

export type AdminDepositAddressesCreateResponse = AdminDepositAddressesCreateResponses[keyof AdminDepositAddressesCreateResponses];

export type AdminDepositFactoriesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/deposit-factories/';
};

export type AdminDepositFactoriesListResponses = {
    200: PaginatedAdminDepositFactoryListResponse;
};

export type AdminDepositFactoriesListResponse = AdminDepositFactoriesListResponses[keyof AdminDepositFactoriesListResponses];

export type AdminDepositFactoriesCreateData = {
    body: AdminCreateDepositFactory;
    path?: never;
    query?: never;
    url: '/admin/deposit-factories/';
};

export type AdminDepositFactoriesCreateResponses = {
    201: AdminDepositFactoryResponse;
};

export type AdminDepositFactoriesCreateResponse = AdminDepositFactoriesCreateResponses[keyof AdminDepositFactoriesCreateResponses];

export type AdminDepositFactoriesRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/deposit-factories/{identifier}/';
};

export type AdminDepositFactoriesRetrieveResponses = {
    200: AdminDepositFactoryResponse;
};

export type AdminDepositFactoriesRetrieveResponse = AdminDepositFactoriesRetrieveResponses[keyof AdminDepositFactoriesRetrieveResponses];

export type AdminOnchainTransactionsListData = {
    body?: never;
    path?: never;
    query?: {
        address?: string;
        /**
         * * `ETH_SEPOLIA` - ETH_SEPOLIA
         * * `ETH_MAINNET` - ETH_MAINNET
         * * `BASE_MAINNET` - BASE_MAINNET
         * * `BASE_SEPOLIA` - BASE_SEPOLIA
         */
        chain?: 'BASE_MAINNET' | 'BASE_SEPOLIA' | 'ETH_MAINNET' | 'ETH_SEPOLIA';
        destination_address?: string;
        from_address?: string;
        hash?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        rehive_transaction_id?: string;
        /**
         * * `pending` - pending
         * * `signed` - signed
         * * `broadcast` - broadcast
         * * `confirmed` - confirmed
         * * `failed` - failed
         * * `cancelled` - cancelled
         */
        status?: 'broadcast' | 'cancelled' | 'confirmed' | 'failed' | 'pending' | 'signed';
        user?: string;
    };
    url: '/admin/onchain-transactions/';
};

export type AdminOnchainTransactionsListResponses = {
    200: PaginatedAdminOnchainTransactionListResponse;
};

export type AdminOnchainTransactionsListResponse = AdminOnchainTransactionsListResponses[keyof AdminOnchainTransactionsListResponses];

export type AdminOnchainTransactionsRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/onchain-transactions/{identifier}/';
};

export type AdminOnchainTransactionsRetrieveResponses = {
    200: AdminOnchainTransactionResponse;
};

export type AdminOnchainTransactionsRetrieveResponse = AdminOnchainTransactionsRetrieveResponses[keyof AdminOnchainTransactionsRetrieveResponses];

export type AlchemyWebhookCreateData = {
    body: AlchemyWebhook;
    path?: never;
    query?: never;
    url: '/alchemy_webhook/';
};

export type AlchemyWebhookCreateResponses = {
    200: ActionResponse;
};

export type AlchemyWebhookCreateResponse = AlchemyWebhookCreateResponses[keyof AlchemyWebhookCreateResponses];

export type DeactivateCreateData = {
    body: Deactivate;
    path?: never;
    query?: never;
    url: '/deactivate/';
};

export type DeactivateCreateResponses = {
    200: ActionResponse;
};

export type DeactivateCreateResponse = DeactivateCreateResponses[keyof DeactivateCreateResponses];

export type UserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserRetrieveResponses = {
    200: UserResponse;
};

export type UserRetrieveResponse = UserRetrieveResponses[keyof UserRetrieveResponses];

export type UserPartialUpdateData = {
    body?: PatchedUserWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserPartialUpdateResponses = {
    200: UserResponse;
};

export type UserPartialUpdateResponse = UserPartialUpdateResponses[keyof UserPartialUpdateResponses];

export type UserUpdateData = {
    body?: UserWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserUpdateResponses = {
    200: UserResponse;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];

export type UserAccountAddressLookupCreateData = {
    body: AccountAddressLookup;
    path?: never;
    query?: never;
    url: '/user/account-address-lookup/';
};

export type UserAccountAddressLookupCreateResponses = {
    200: AccountAddressLookupResponse;
};

export type UserAccountAddressLookupCreateResponse = UserAccountAddressLookupCreateResponses[keyof UserAccountAddressLookupCreateResponses];

export type UserAddressesListData = {
    body?: never;
    path?: never;
    query?: {
        address?: string;
        has_parent?: boolean;
        has_rehive_account?: boolean;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        provider?: string;
        rehive_account?: string;
        subtype?: string;
    };
    url: '/user/addresses/';
};

export type UserAddressesListResponses = {
    200: PaginatedAddressListResponse;
};

export type UserAddressesListResponse = UserAddressesListResponses[keyof UserAddressesListResponses];

export type UserAddressesCreateData = {
    body?: UserCreateAddressWritable;
    path?: never;
    query?: never;
    url: '/user/addresses/';
};

export type UserAddressesCreateResponses = {
    201: AddressResponse;
};

export type UserAddressesCreateResponse = UserAddressesCreateResponses[keyof UserAddressesCreateResponses];

export type UserAddressesRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/addresses/{identifier}/';
};

export type UserAddressesRetrieveResponses = {
    200: AddressResponse;
};

export type UserAddressesRetrieveResponse = UserAddressesRetrieveResponses[keyof UserAddressesRetrieveResponses];

export type UserCollectionsRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/collections/{identifier}/';
};

export type UserCollectionsRetrieveResponses = {
    200: TransactionCollectionResponse;
};

export type UserCollectionsRetrieveResponse = UserCollectionsRetrieveResponses[keyof UserCollectionsRetrieveResponses];

export type UserCollectionsPartialUpdateData = {
    body?: PatchedTransactionCollectionWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/collections/{identifier}/';
};

export type UserCollectionsPartialUpdateResponses = {
    200: TransactionCollectionResponse;
};

export type UserCollectionsPartialUpdateResponse = UserCollectionsPartialUpdateResponses[keyof UserCollectionsPartialUpdateResponses];

export type UserCollectionsUpdateData = {
    body: TransactionCollectionWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/collections/{identifier}/';
};

export type UserCollectionsUpdateResponses = {
    200: TransactionCollectionResponse;
};

export type UserCollectionsUpdateResponse = UserCollectionsUpdateResponses[keyof UserCollectionsUpdateResponses];

export type UserOnchainTransactionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/user/onchain-transactions/';
};

export type UserOnchainTransactionsListResponses = {
    200: PaginatedOnchainTransactionListResponse;
};

export type UserOnchainTransactionsListResponse = UserOnchainTransactionsListResponses[keyof UserOnchainTransactionsListResponses];

export type UserOnchainTransactionsRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/onchain-transactions/{identifier}/';
};

export type UserOnchainTransactionsRetrieveResponses = {
    200: OnchainTransactionResponse;
};

export type UserOnchainTransactionsRetrieveResponse = UserOnchainTransactionsRetrieveResponses[keyof UserOnchainTransactionsRetrieveResponses];

export type UserOnchainTransactionsPartialUpdateData = {
    body?: PatchedOnchainTransactionWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/onchain-transactions/{identifier}/';
};

export type UserOnchainTransactionsPartialUpdateResponses = {
    200: OnchainTransactionResponse;
};

export type UserOnchainTransactionsPartialUpdateResponse = UserOnchainTransactionsPartialUpdateResponses[keyof UserOnchainTransactionsPartialUpdateResponses];

export type UserOnchainTransactionsUpdateData = {
    body: OnchainTransactionWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/onchain-transactions/{identifier}/';
};

export type UserOnchainTransactionsUpdateResponses = {
    200: OnchainTransactionResponse;
};

export type UserOnchainTransactionsUpdateResponse = UserOnchainTransactionsUpdateResponses[keyof UserOnchainTransactionsUpdateResponses];

export type UserOnchainTransactionsCancelCreateData = {
    body?: ActionResponse;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/user/onchain-transactions/{identifier}/cancel/';
};

export type UserOnchainTransactionsCancelCreateResponses = {
    200: OnchainTransactionResponse;
};

export type UserOnchainTransactionsCancelCreateResponse = UserOnchainTransactionsCancelCreateResponses[keyof UserOnchainTransactionsCancelCreateResponses];

export type WebhookCreateData = {
    body: Webhook;
    path?: never;
    query?: never;
    url: '/webhook/';
};

export type WebhookCreateResponses = {
    200: ActionResponse;
};

export type WebhookCreateResponse = WebhookCreateResponses[keyof WebhookCreateResponses];
