// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateCreateData, ActivateCreateResponses, AdminCardsListData, AdminCardsListResponses, AdminCardsRetrieveData, AdminCardsRetrieveResponses, AdminCompanyPartialUpdateData, AdminCompanyPartialUpdateResponses, AdminCompanyRetrieveData, AdminCompanyRetrieveResponses, AdminCompanyUpdateData, AdminCompanyUpdateResponses, AdminCurrenciesListData, AdminCurrenciesListResponses, AdminCurrenciesPartialUpdateData, AdminCurrenciesPartialUpdateResponses, AdminCurrenciesRetrieveData, AdminCurrenciesRetrieveResponses, AdminCurrenciesUpdateData, AdminCurrenciesUpdateResponses, DeactivateCreateData, DeactivateCreateResponses, RainWebhookCreateData, RainWebhookCreateResponses, UserApplicationsCreateData, UserApplicationsCreateResponses, UserApplicationsListData, UserApplicationsListResponses, UserApplicationsRetrieveData, UserApplicationsRetrieveResponses, UserCardsCreateData, UserCardsCreateResponses, UserCardsDataRetrieveData, UserCardsDataRetrieveResponses, UserCardsListData, UserCardsListResponses, UserCardsPinPartialUpdateData, UserCardsPinPartialUpdateResponses, UserCardsPinRetrieveData, UserCardsPinRetrieveResponses, UserCardsPinUpdateData, UserCardsPinUpdateResponses, UserCardsRetrieveData, UserCardsRetrieveResponses, UserPartialUpdateData, UserPartialUpdateResponses, UserRetrieveData, UserRetrieveResponses, UserUpdateData, UserUpdateResponses, WebhookCreateData, WebhookCreateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const activateCreate = <ThrowOnError extends boolean = false>(options: Options<ActivateCreateData, ThrowOnError>) => (options.client ?? client).post<ActivateCreateResponses, unknown, ThrowOnError>({
    url: '/activate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const adminCardsList = <ThrowOnError extends boolean = false>(options?: Options<AdminCardsListData, ThrowOnError>) => (options?.client ?? client).get<AdminCardsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/cards/',
    ...options
});

export const adminCardsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminCardsRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminCardsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/cards/{identifier}/',
    ...options
});

export const adminCompanyRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyRetrieveData, ThrowOnError>) => (options?.client ?? client).get<AdminCompanyRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options
});

export const adminCompanyPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyPartialUpdateData, ThrowOnError>) => (options?.client ?? client).patch<AdminCompanyPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const adminCompanyUpdate = <ThrowOnError extends boolean = false>(options?: Options<AdminCompanyUpdateData, ThrowOnError>) => (options?.client ?? client).put<AdminCompanyUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/company/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const adminCurrenciesList = <ThrowOnError extends boolean = false>(options?: Options<AdminCurrenciesListData, ThrowOnError>) => (options?.client ?? client).get<AdminCurrenciesListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/',
    ...options
});

export const adminCurrenciesRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdminCurrenciesRetrieveData, ThrowOnError>) => (options.client ?? client).get<AdminCurrenciesRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/{code}/',
    ...options
});

export const adminCurrenciesPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminCurrenciesPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<AdminCurrenciesPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/{code}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const adminCurrenciesUpdate = <ThrowOnError extends boolean = false>(options: Options<AdminCurrenciesUpdateData, ThrowOnError>) => (options.client ?? client).put<AdminCurrenciesUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/currencies/{code}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deactivateCreate = <ThrowOnError extends boolean = false>(options: Options<DeactivateCreateData, ThrowOnError>) => (options.client ?? client).post<DeactivateCreateResponses, unknown, ThrowOnError>({
    url: '/deactivate/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const rainWebhookCreate = <ThrowOnError extends boolean = false>(options: Options<RainWebhookCreateData, ThrowOnError>) => (options.client ?? client).post<RainWebhookCreateResponses, unknown, ThrowOnError>({
    url: '/rain/webhook/{company_id}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userRetrieve = <ThrowOnError extends boolean = false>(options?: Options<UserRetrieveData, ThrowOnError>) => (options?.client ?? client).get<UserRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options
});

export const userPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<UserPartialUpdateData, ThrowOnError>) => (options?.client ?? client).patch<UserPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const userUpdate = <ThrowOnError extends boolean = false>(options?: Options<UserUpdateData, ThrowOnError>) => (options?.client ?? client).put<UserUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const userApplicationsList = <ThrowOnError extends boolean = false>(options?: Options<UserApplicationsListData, ThrowOnError>) => (options?.client ?? client).get<UserApplicationsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/applications/',
    ...options
});

export const userApplicationsCreate = <ThrowOnError extends boolean = false>(options: Options<UserApplicationsCreateData, ThrowOnError>) => (options.client ?? client).post<UserApplicationsCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/applications/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userApplicationsRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserApplicationsRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserApplicationsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/applications/{identifier}/',
    ...options
});

export const userCardsList = <ThrowOnError extends boolean = false>(options?: Options<UserCardsListData, ThrowOnError>) => (options?.client ?? client).get<UserCardsListResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/',
    ...options
});

export const userCardsCreate = <ThrowOnError extends boolean = false>(options: Options<UserCardsCreateData, ThrowOnError>) => (options.client ?? client).post<UserCardsCreateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userCardsRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserCardsRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserCardsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/{identifier}/',
    ...options
});

export const userCardsDataRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserCardsDataRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserCardsDataRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/{identifier}/data/',
    ...options
});

export const userCardsPinRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserCardsPinRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserCardsPinRetrieveResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/{identifier}/pin/',
    ...options
});

export const userCardsPinPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UserCardsPinPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<UserCardsPinPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/{identifier}/pin/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userCardsPinUpdate = <ThrowOnError extends boolean = false>(options: Options<UserCardsPinUpdateData, ThrowOnError>) => (options.client ?? client).put<UserCardsPinUpdateResponses, unknown, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user/cards/{identifier}/pin/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const webhookCreate = <ThrowOnError extends boolean = false>(options: Options<WebhookCreateData, ThrowOnError>) => (options.client ?? client).post<WebhookCreateResponses, unknown, ThrowOnError>({
    url: '/webhook/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
