// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://app.services.rehive.com/api/' | (string & {});
};

/**
 * This serializer can be used if only a `status` is required in the response.
 */
export type ActionResponse = {
    status?: string;
};

export type Activate = {
    token: string;
    readonly id: string;
    readonly secret: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompany = {
    readonly id: string;
    readonly secret: string;
    config?: {
        [key: string]: unknown;
    } | null;
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
    readonly domains: Array<string> | null;
};

export type AdminCompanyResponse = {
    status?: string;
    data?: AdminCompany;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateDomain = {
    readonly id: string;
    /**
     * * `native` - Native
     * * `client` - Client
     */
    host?: 'native' | 'client';
    domain: string;
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     */
    status: 'active' | 'inactive';
    readonly created: number;
    readonly updated: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateLocale = {
    id: string;
    translation: {
        [key: string]: unknown;
    };
    icon?: string | null;
    name?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminDomain = {
    readonly id: string;
    /**
     * * `native` - Native
     * * `client` - Client
     */
    host: 'native' | 'client';
    readonly domain: string;
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     */
    status: 'active' | 'inactive';
    readonly created: number;
    readonly updated: number;
};

export type AdminDomainResponse = {
    status?: string;
    data?: AdminDomain;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AndroidApp = {
    readonly id: string;
    package: string;
    name?: string | null;
    short_description?: string | null;
    full_description?: string | null;
    whats_new?: string | null;
    website?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
    readonly created: number;
    readonly updated: number;
};

export type AndroidAppResponse = {
    status?: string;
    data?: AndroidApp;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AppCodebase = {
    readonly id: string;
    /**
     * * `mobile` - Mobile
     * * `web` - Web
     */
    type: 'mobile' | 'web';
    file: string;
    version: string;
    title?: string | null;
    description?: string | null;
    readonly created: string;
    readonly updated: string;
};

export type AppCodebaseResponse = {
    status?: string;
    data?: AppCodebase;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Company = {
    readonly id: string;
    readonly config: {
        [key: string]: unknown;
    };
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
    readonly domains: Array<string> | null;
};

export type CompanyResponse = {
    status?: string;
    data?: Company;
};

export type Deactivate = {
    token: string;
    purge?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type IosApp = {
    readonly id: string;
    bundle_identifier: string;
    name?: string | null;
    subtitle?: string | null;
    description?: string | null;
    promotional_text?: string | null;
    whats_new?: string | null;
    keywords?: string | null;
    support_url?: string | null;
    marketing_url?: string | null;
    contact_first_name?: string | null;
    contact_last_name?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    copyright?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
    readonly created: number;
    readonly updated: number;
};

export type IosAppResponse = {
    status?: string;
    data?: IosApp;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type Locale = {
    readonly id: string;
    translation: {
        [key: string]: unknown;
    };
    readonly created: number;
    readonly updated: number;
    icon?: string | null;
    name?: string | null;
};

export type LocaleResponse = {
    status?: string;
    data?: Locale;
};

export type PaginatedAdminDomainList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminDomain>;
};

export type PaginatedAdminDomainListResponse = {
    status?: string;
    data?: PaginatedAdminDomainList;
};

export type PaginatedAndroidAppList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AndroidApp>;
};

export type PaginatedAndroidAppListResponse = {
    status?: string;
    data?: PaginatedAndroidAppList;
};

export type PaginatedAppCodebaseList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AppCodebase>;
};

export type PaginatedAppCodebaseListResponse = {
    status?: string;
    data?: PaginatedAppCodebaseList;
};

export type PaginatedIosAppList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<IosApp>;
};

export type PaginatedIosAppListResponse = {
    status?: string;
    data?: PaginatedIosAppList;
};

export type PaginatedLocaleList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Locale>;
};

export type PaginatedLocaleListResponse = {
    status?: string;
    data?: PaginatedLocaleList;
};

export type PaginatedUserAndroidAppList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserAndroidApp>;
};

export type PaginatedUserAndroidAppListResponse = {
    status?: string;
    data?: PaginatedUserAndroidAppList;
};

export type PaginatedUserIosAppList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<UserIosApp>;
};

export type PaginatedUserIosAppListResponse = {
    status?: string;
    data?: PaginatedUserIosAppList;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompany = {
    readonly id?: string;
    readonly secret?: string;
    config?: {
        [key: string]: unknown;
    } | null;
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
    readonly domains?: Array<string> | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminDomain = {
    readonly id?: string;
    /**
     * * `native` - Native
     * * `client` - Client
     */
    host?: 'native' | 'client';
    readonly domain?: string;
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     */
    status?: 'active' | 'inactive';
    readonly created?: number;
    readonly updated?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAndroidApp = {
    readonly id?: string;
    package?: string;
    name?: string | null;
    short_description?: string | null;
    full_description?: string | null;
    whats_new?: string | null;
    website?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
    readonly created?: number;
    readonly updated?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAppCodebase = {
    readonly id?: string;
    /**
     * * `mobile` - Mobile
     * * `web` - Web
     */
    type?: 'mobile' | 'web';
    file?: string;
    version?: string;
    title?: string | null;
    description?: string | null;
    readonly created?: string;
    readonly updated?: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedIosApp = {
    readonly id?: string;
    bundle_identifier?: string;
    name?: string | null;
    subtitle?: string | null;
    description?: string | null;
    promotional_text?: string | null;
    whats_new?: string | null;
    keywords?: string | null;
    support_url?: string | null;
    marketing_url?: string | null;
    contact_first_name?: string | null;
    contact_last_name?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    copyright?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
    readonly created?: number;
    readonly updated?: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedLocale = {
    readonly id?: string;
    translation?: {
        [key: string]: unknown;
    };
    readonly created?: number;
    readonly updated?: number;
    icon?: string | null;
    name?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUser = {
    readonly id?: string;
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type User = {
    readonly id: string;
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserAndroidApp = {
    readonly id: string;
    readonly package: string;
    readonly name: string | null;
    readonly short_description: string | null;
    readonly full_description: string | null;
    readonly whats_new: string | null;
    readonly website: string | null;
    readonly contact_phone_number: string | null;
    readonly contact_email_address: string | null;
    readonly terms_and_conditions: string | null;
    readonly privacy_policy: string | null;
    readonly expo_project_id: string | null;
    readonly created: number;
    readonly updated: number;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserIosApp = {
    readonly id: string;
    readonly bundle_identifier: string;
    readonly name: string | null;
    readonly subtitle: string | null;
    readonly description: string | null;
    readonly promotional_text: string | null;
    readonly whats_new: string | null;
    readonly keywords: string | null;
    readonly support_url: string | null;
    readonly marketing_url: string | null;
    readonly contact_first_name: string | null;
    readonly contact_last_name: string | null;
    readonly contact_phone_number: string | null;
    readonly contact_email_address: string | null;
    readonly copyright: string | null;
    readonly terms_and_conditions: string | null;
    readonly privacy_policy: string | null;
    readonly expo_project_id: string | null;
    readonly created: number;
    readonly updated: number;
};

export type UserResponse = {
    status?: string;
    data?: User;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompanyWritable = {
    config?: {
        [key: string]: unknown;
    } | null;
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
};

export type AdminCompanyResponseWritable = {
    status?: string;
    data?: AdminCompanyWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCreateDomainWritable = {
    /**
     * * `native` - Native
     * * `client` - Client
     */
    host?: 'native' | 'client';
    domain: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminDomainWritable = {
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     */
    status: 'active' | 'inactive';
};

export type AdminDomainResponseWritable = {
    status?: string;
    data?: AdminDomainWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AndroidAppWritable = {
    package: string;
    name?: string | null;
    short_description?: string | null;
    full_description?: string | null;
    whats_new?: string | null;
    website?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
};

export type AndroidAppResponseWritable = {
    status?: string;
    data?: AndroidAppWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AppCodebaseWritable = {
    /**
     * * `mobile` - Mobile
     * * `web` - Web
     */
    type: 'mobile' | 'web';
    file: string;
    version: string;
    title?: string | null;
    description?: string | null;
};

export type AppCodebaseResponseWritable = {
    status?: string;
    data?: AppCodebaseWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type CompanyWritable = {
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
};

export type CompanyResponseWritable = {
    status?: string;
    data?: CompanyWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type IosAppWritable = {
    bundle_identifier: string;
    name?: string | null;
    subtitle?: string | null;
    description?: string | null;
    promotional_text?: string | null;
    whats_new?: string | null;
    keywords?: string | null;
    support_url?: string | null;
    marketing_url?: string | null;
    contact_first_name?: string | null;
    contact_last_name?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    copyright?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
};

export type IosAppResponseWritable = {
    status?: string;
    data?: IosAppWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type LocaleWritable = {
    translation: {
        [key: string]: unknown;
    };
    icon?: string | null;
    name?: string | null;
};

export type LocaleResponseWritable = {
    status?: string;
    data?: LocaleWritable;
};

export type PaginatedAdminDomainListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminDomainWritable>;
};

export type PaginatedAdminDomainListResponseWritable = {
    status?: string;
    data?: PaginatedAdminDomainListWritable;
};

export type PaginatedAndroidAppListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AndroidAppWritable>;
};

export type PaginatedAndroidAppListResponseWritable = {
    status?: string;
    data?: PaginatedAndroidAppListWritable;
};

export type PaginatedAppCodebaseListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AppCodebaseWritable>;
};

export type PaginatedAppCodebaseListResponseWritable = {
    status?: string;
    data?: PaginatedAppCodebaseListWritable;
};

export type PaginatedIosAppListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<IosAppWritable>;
};

export type PaginatedIosAppListResponseWritable = {
    status?: string;
    data?: PaginatedIosAppListWritable;
};

export type PaginatedLocaleListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<LocaleWritable>;
};

export type PaginatedLocaleListResponseWritable = {
    status?: string;
    data?: PaginatedLocaleListWritable;
};

export type PaginatedUserAndroidAppListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<unknown>;
};

export type PaginatedUserAndroidAppListResponseWritable = {
    status?: string;
    data?: PaginatedUserAndroidAppListWritable;
};

export type PaginatedUserIosAppListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<unknown>;
};

export type PaginatedUserIosAppListResponseWritable = {
    status?: string;
    data?: PaginatedUserIosAppListWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompanyWritable = {
    config?: {
        [key: string]: unknown;
    } | null;
    android_play_store_url?: string | null;
    apple_app_store_url?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminDomainWritable = {
    /**
     * * `active` - Active
     * * `inactive` - Inactive
     */
    status?: 'active' | 'inactive';
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAndroidAppWritable = {
    package?: string;
    name?: string | null;
    short_description?: string | null;
    full_description?: string | null;
    whats_new?: string | null;
    website?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAppCodebaseWritable = {
    /**
     * * `mobile` - Mobile
     * * `web` - Web
     */
    type?: 'mobile' | 'web';
    file?: string;
    version?: string;
    title?: string | null;
    description?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedIosAppWritable = {
    bundle_identifier?: string;
    name?: string | null;
    subtitle?: string | null;
    description?: string | null;
    promotional_text?: string | null;
    whats_new?: string | null;
    keywords?: string | null;
    support_url?: string | null;
    marketing_url?: string | null;
    contact_first_name?: string | null;
    contact_last_name?: string | null;
    contact_phone_number?: string | null;
    contact_email_address?: string | null;
    copyright?: string | null;
    terms_and_conditions?: string | null;
    privacy_policy?: string | null;
    expo_project_id?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedLocaleWritable = {
    translation?: {
        [key: string]: unknown;
    };
    icon?: string | null;
    name?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedUserWritable = {
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type UserWritable = {
    config?: {
        [key: string]: unknown;
    } | null;
};

export type UserResponseWritable = {
    status?: string;
    data?: UserWritable;
};

export type ActivateCreateData = {
    body: Activate;
    path?: never;
    query?: never;
    url: '/activate/';
};

export type ActivateCreateResponses = {
    200: ActionResponse;
};

export type ActivateCreateResponse = ActivateCreateResponses[keyof ActivateCreateResponses];

export type AdminAndroidAppsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/android-apps/';
};

export type AdminAndroidAppsListResponses = {
    200: PaginatedAndroidAppListResponse;
};

export type AdminAndroidAppsListResponse = AdminAndroidAppsListResponses[keyof AdminAndroidAppsListResponses];

export type AdminAndroidAppsCreateData = {
    body: AndroidAppWritable;
    path?: never;
    query?: never;
    url: '/admin/android-apps/';
};

export type AdminAndroidAppsCreateResponses = {
    201: AndroidAppResponse;
};

export type AdminAndroidAppsCreateResponse = AdminAndroidAppsCreateResponses[keyof AdminAndroidAppsCreateResponses];

export type AdminAndroidAppsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/android-apps/{id}/';
};

export type AdminAndroidAppsDestroyResponses = {
    200: AndroidAppResponse;
};

export type AdminAndroidAppsDestroyResponse = AdminAndroidAppsDestroyResponses[keyof AdminAndroidAppsDestroyResponses];

export type AdminAndroidAppsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/android-apps/{id}/';
};

export type AdminAndroidAppsRetrieveResponses = {
    200: AndroidAppResponse;
};

export type AdminAndroidAppsRetrieveResponse = AdminAndroidAppsRetrieveResponses[keyof AdminAndroidAppsRetrieveResponses];

export type AdminAndroidAppsPartialUpdateData = {
    body?: PatchedAndroidAppWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/android-apps/{id}/';
};

export type AdminAndroidAppsPartialUpdateResponses = {
    200: AndroidAppResponse;
};

export type AdminAndroidAppsPartialUpdateResponse = AdminAndroidAppsPartialUpdateResponses[keyof AdminAndroidAppsPartialUpdateResponses];

export type AdminAndroidAppsUpdateData = {
    body: AndroidAppWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/android-apps/{id}/';
};

export type AdminAndroidAppsUpdateResponses = {
    200: AndroidAppResponse;
};

export type AdminAndroidAppsUpdateResponse = AdminAndroidAppsUpdateResponses[keyof AdminAndroidAppsUpdateResponses];

export type AdminAppCodebasesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        type?: string;
        version?: string;
    };
    url: '/admin/app-codebases/';
};

export type AdminAppCodebasesListResponses = {
    200: PaginatedAppCodebaseListResponse;
};

export type AdminAppCodebasesListResponse = AdminAppCodebasesListResponses[keyof AdminAppCodebasesListResponses];

export type AdminAppCodebasesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/app-codebases/{id}/';
};

export type AdminAppCodebasesRetrieveResponses = {
    200: AppCodebaseResponse;
};

export type AdminAppCodebasesRetrieveResponse = AdminAppCodebasesRetrieveResponses[keyof AdminAppCodebasesRetrieveResponses];

export type AdminCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyRetrieveResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyRetrieveResponse = AdminCompanyRetrieveResponses[keyof AdminCompanyRetrieveResponses];

export type AdminCompanyPartialUpdateData = {
    body?: PatchedAdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyPartialUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyPartialUpdateResponse = AdminCompanyPartialUpdateResponses[keyof AdminCompanyPartialUpdateResponses];

export type AdminCompanyUpdateData = {
    body?: AdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyUpdateResponse = AdminCompanyUpdateResponses[keyof AdminCompanyUpdateResponses];

export type AdminDomainsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/domains/';
};

export type AdminDomainsListResponses = {
    200: PaginatedAdminDomainListResponse;
};

export type AdminDomainsListResponse = AdminDomainsListResponses[keyof AdminDomainsListResponses];

export type AdminDomainsCreateData = {
    body: AdminCreateDomainWritable;
    path?: never;
    query?: never;
    url: '/admin/domains/';
};

export type AdminDomainsCreateResponses = {
    201: AdminDomainResponse;
};

export type AdminDomainsCreateResponse = AdminDomainsCreateResponses[keyof AdminDomainsCreateResponses];

export type AdminDomainsDestroyData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/domains/{identifier}/';
};

export type AdminDomainsDestroyResponses = {
    200: AdminDomainResponse;
};

export type AdminDomainsDestroyResponse = AdminDomainsDestroyResponses[keyof AdminDomainsDestroyResponses];

export type AdminDomainsRetrieveData = {
    body?: never;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/domains/{identifier}/';
};

export type AdminDomainsRetrieveResponses = {
    200: AdminDomainResponse;
};

export type AdminDomainsRetrieveResponse = AdminDomainsRetrieveResponses[keyof AdminDomainsRetrieveResponses];

export type AdminDomainsPartialUpdateData = {
    body?: PatchedAdminDomainWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/domains/{identifier}/';
};

export type AdminDomainsPartialUpdateResponses = {
    200: AdminDomainResponse;
};

export type AdminDomainsPartialUpdateResponse = AdminDomainsPartialUpdateResponses[keyof AdminDomainsPartialUpdateResponses];

export type AdminDomainsUpdateData = {
    body: AdminDomainWritable;
    path: {
        identifier: string;
    };
    query?: never;
    url: '/admin/domains/{identifier}/';
};

export type AdminDomainsUpdateResponses = {
    200: AdminDomainResponse;
};

export type AdminDomainsUpdateResponse = AdminDomainsUpdateResponses[keyof AdminDomainsUpdateResponses];

export type AdminIosAppsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/ios-apps/';
};

export type AdminIosAppsListResponses = {
    200: PaginatedIosAppListResponse;
};

export type AdminIosAppsListResponse = AdminIosAppsListResponses[keyof AdminIosAppsListResponses];

export type AdminIosAppsCreateData = {
    body: IosAppWritable;
    path?: never;
    query?: never;
    url: '/admin/ios-apps/';
};

export type AdminIosAppsCreateResponses = {
    201: IosAppResponse;
};

export type AdminIosAppsCreateResponse = AdminIosAppsCreateResponses[keyof AdminIosAppsCreateResponses];

export type AdminIosAppsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/ios-apps/{id}/';
};

export type AdminIosAppsDestroyResponses = {
    200: IosAppResponse;
};

export type AdminIosAppsDestroyResponse = AdminIosAppsDestroyResponses[keyof AdminIosAppsDestroyResponses];

export type AdminIosAppsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/ios-apps/{id}/';
};

export type AdminIosAppsRetrieveResponses = {
    200: IosAppResponse;
};

export type AdminIosAppsRetrieveResponse = AdminIosAppsRetrieveResponses[keyof AdminIosAppsRetrieveResponses];

export type AdminIosAppsPartialUpdateData = {
    body?: PatchedIosAppWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/ios-apps/{id}/';
};

export type AdminIosAppsPartialUpdateResponses = {
    200: IosAppResponse;
};

export type AdminIosAppsPartialUpdateResponse = AdminIosAppsPartialUpdateResponses[keyof AdminIosAppsPartialUpdateResponses];

export type AdminIosAppsUpdateData = {
    body: IosAppWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/ios-apps/{id}/';
};

export type AdminIosAppsUpdateResponses = {
    200: IosAppResponse;
};

export type AdminIosAppsUpdateResponse = AdminIosAppsUpdateResponses[keyof AdminIosAppsUpdateResponses];

export type AdminLocalesListData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        id__in?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/locales/';
};

export type AdminLocalesListResponses = {
    200: PaginatedLocaleListResponse;
};

export type AdminLocalesListResponse = AdminLocalesListResponses[keyof AdminLocalesListResponses];

export type AdminLocalesCreateData = {
    body: AdminCreateLocale;
    path?: never;
    query?: never;
    url: '/admin/locales/';
};

export type AdminLocalesCreateResponses = {
    201: LocaleResponse;
};

export type AdminLocalesCreateResponse = AdminLocalesCreateResponses[keyof AdminLocalesCreateResponses];

export type AdminLocalesDestroyData = {
    body?: never;
    path: {
        locale_id: string;
    };
    query?: never;
    url: '/admin/locales/{locale_id}/';
};

export type AdminLocalesDestroyResponses = {
    200: LocaleResponse;
};

export type AdminLocalesDestroyResponse = AdminLocalesDestroyResponses[keyof AdminLocalesDestroyResponses];

export type AdminLocalesRetrieveData = {
    body?: never;
    path: {
        locale_id: string;
    };
    query?: never;
    url: '/admin/locales/{locale_id}/';
};

export type AdminLocalesRetrieveResponses = {
    200: LocaleResponse;
};

export type AdminLocalesRetrieveResponse = AdminLocalesRetrieveResponses[keyof AdminLocalesRetrieveResponses];

export type AdminLocalesPartialUpdateData = {
    body?: PatchedLocaleWritable;
    path: {
        locale_id: string;
    };
    query?: never;
    url: '/admin/locales/{locale_id}/';
};

export type AdminLocalesPartialUpdateResponses = {
    200: LocaleResponse;
};

export type AdminLocalesPartialUpdateResponse = AdminLocalesPartialUpdateResponses[keyof AdminLocalesPartialUpdateResponses];

export type AdminLocalesUpdateData = {
    body: LocaleWritable;
    path: {
        locale_id: string;
    };
    query?: never;
    url: '/admin/locales/{locale_id}/';
};

export type AdminLocalesUpdateResponses = {
    200: LocaleResponse;
};

export type AdminLocalesUpdateResponse = AdminLocalesUpdateResponses[keyof AdminLocalesUpdateResponses];

export type DeactivateCreateData = {
    body: Deactivate;
    path?: never;
    query?: never;
    url: '/deactivate/';
};

export type DeactivateCreateResponses = {
    200: ActionResponse;
};

export type DeactivateCreateResponse = DeactivateCreateResponses[keyof DeactivateCreateResponses];

export type PublicCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/company/';
};

export type PublicCompanyRetrieveResponses = {
    200: CompanyResponse;
};

export type PublicCompanyRetrieveResponse = PublicCompanyRetrieveResponses[keyof PublicCompanyRetrieveResponses];

export type PublicCompanyLocalesListData = {
    body?: never;
    path: {
        company_id: string;
    };
    query?: {
        id?: string;
        id__in?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/public/company/{company_id}/locales/';
};

export type PublicCompanyLocalesListResponses = {
    200: PaginatedLocaleListResponse;
};

export type PublicCompanyLocalesListResponse = PublicCompanyLocalesListResponses[keyof PublicCompanyLocalesListResponses];

export type PublicCompanyLocalesRetrieveData = {
    body?: never;
    path: {
        company_id: string;
        locale_id: string;
    };
    query?: never;
    url: '/public/company/{company_id}/locales/{locale_id}/';
};

export type PublicCompanyLocalesRetrieveResponses = {
    200: LocaleResponse;
};

export type PublicCompanyLocalesRetrieveResponse = PublicCompanyLocalesRetrieveResponses[keyof PublicCompanyLocalesRetrieveResponses];

export type SuperadminAppCodebasesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        type?: string;
        version?: string;
    };
    url: '/superadmin/app-codebases/';
};

export type SuperadminAppCodebasesListResponses = {
    200: PaginatedAppCodebaseListResponse;
};

export type SuperadminAppCodebasesListResponse = SuperadminAppCodebasesListResponses[keyof SuperadminAppCodebasesListResponses];

export type SuperadminAppCodebasesCreateData = {
    body: AppCodebaseWritable;
    path?: never;
    query?: never;
    url: '/superadmin/app-codebases/';
};

export type SuperadminAppCodebasesCreateResponses = {
    201: AppCodebaseResponse;
};

export type SuperadminAppCodebasesCreateResponse = SuperadminAppCodebasesCreateResponses[keyof SuperadminAppCodebasesCreateResponses];

export type SuperadminAppCodebasesDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/superadmin/app-codebases/{id}/';
};

export type SuperadminAppCodebasesDestroyResponses = {
    200: AppCodebaseResponse;
};

export type SuperadminAppCodebasesDestroyResponse = SuperadminAppCodebasesDestroyResponses[keyof SuperadminAppCodebasesDestroyResponses];

export type SuperadminAppCodebasesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/superadmin/app-codebases/{id}/';
};

export type SuperadminAppCodebasesRetrieveResponses = {
    200: AppCodebaseResponse;
};

export type SuperadminAppCodebasesRetrieveResponse = SuperadminAppCodebasesRetrieveResponses[keyof SuperadminAppCodebasesRetrieveResponses];

export type SuperadminAppCodebasesPartialUpdateData = {
    body?: PatchedAppCodebaseWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/superadmin/app-codebases/{id}/';
};

export type SuperadminAppCodebasesPartialUpdateResponses = {
    200: AppCodebaseResponse;
};

export type SuperadminAppCodebasesPartialUpdateResponse = SuperadminAppCodebasesPartialUpdateResponses[keyof SuperadminAppCodebasesPartialUpdateResponses];

export type SuperadminAppCodebasesUpdateData = {
    body: AppCodebaseWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/superadmin/app-codebases/{id}/';
};

export type SuperadminAppCodebasesUpdateResponses = {
    200: AppCodebaseResponse;
};

export type SuperadminAppCodebasesUpdateResponse = SuperadminAppCodebasesUpdateResponses[keyof SuperadminAppCodebasesUpdateResponses];

export type UserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserRetrieveResponses = {
    200: UserResponse;
};

export type UserRetrieveResponse = UserRetrieveResponses[keyof UserRetrieveResponses];

export type UserPartialUpdateData = {
    body?: PatchedUserWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserPartialUpdateResponses = {
    200: UserResponse;
};

export type UserPartialUpdateResponse = UserPartialUpdateResponses[keyof UserPartialUpdateResponses];

export type UserUpdateData = {
    body?: UserWritable;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UserUpdateResponses = {
    200: UserResponse;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];

export type UserAndroidAppsListData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        package?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/user/android-apps/';
};

export type UserAndroidAppsListResponses = {
    200: PaginatedUserAndroidAppListResponse;
};

export type UserAndroidAppsListResponse = UserAndroidAppsListResponses[keyof UserAndroidAppsListResponses];

export type UserCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/company/';
};

export type UserCompanyRetrieveResponses = {
    200: CompanyResponse;
};

export type UserCompanyRetrieveResponse = UserCompanyRetrieveResponses[keyof UserCompanyRetrieveResponses];

export type UserIosAppsListData = {
    body?: never;
    path?: never;
    query?: {
        bundle_identifier?: string;
        id?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/user/ios-apps/';
};

export type UserIosAppsListResponses = {
    200: PaginatedUserIosAppListResponse;
};

export type UserIosAppsListResponse = UserIosAppsListResponses[keyof UserIosAppsListResponses];

export type UserLocalesListData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        id__in?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/user/locales/';
};

export type UserLocalesListResponses = {
    200: PaginatedLocaleListResponse;
};

export type UserLocalesListResponse = UserLocalesListResponses[keyof UserLocalesListResponses];

export type UserLocalesRetrieveData = {
    body?: never;
    path: {
        locale_id: string;
    };
    query?: never;
    url: '/user/locales/{locale_id}/';
};

export type UserLocalesRetrieveResponses = {
    200: LocaleResponse;
};

export type UserLocalesRetrieveResponse = UserLocalesRetrieveResponses[keyof UserLocalesRetrieveResponses];
