// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://mass-send.services.rehive.com/api/1/' | (string & {});
};

/**
 * This serializer can be used if only a `status` is required in the response.
 */
export type ActionResponse = {
    status?: string;
};

/**
 * Serialize the activation data, should be a token that represents an admin
 * user.
 */
export type Activate = {
    token: string;
    readonly id: string;
    readonly name: string;
    readonly secret: string;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompany = {
    readonly id: string;
    readonly secret: string;
    name?: string | null;
};

export type AdminCompanyResponse = {
    status?: string;
    data?: AdminCompany;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminListCreateTransactionBatch = {
    readonly id: string;
    file: string;
    readonly file_hash: string | null;
    readonly transactions_total: number;
    readonly transactions_succeeded: number;
    readonly transactions_failed: number;
    readonly created: number;
    readonly updated: number;
    readonly status: string;
    readonly errors: Array<string>;
    published?: boolean;
    /**
     * * `admin` - Admin
     * * `user` - User
     */
    section: 'admin' | 'user';
};

export type AdminListCreateTransactionBatchResponse = {
    status?: string;
    data?: AdminListCreateTransactionBatch;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminListCreateTransactionUpdateBatch = {
    readonly id: string;
    file: string;
    readonly file_hash: string | null;
    readonly rows_total: number;
    readonly rows_succeeded: number;
    readonly rows_failed: number;
    readonly created: number;
    readonly updated: number;
    readonly status: string;
    readonly errors: Array<string>;
    published?: boolean;
    /**
     * * `admin` - Admin
     */
    section?: 'admin';
};

export type AdminListCreateTransactionUpdateBatchResponse = {
    status?: string;
    data?: AdminListCreateTransactionUpdateBatch;
};

/**
 * Serialize the deactivation data, should be a token that represents an admin
 * user.
 */
export type Deactivate = {
    token: string;
    purge?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListCreateTransactionBatch = {
    readonly id: string;
    file: string;
    readonly file_hash: string | null;
    readonly transactions_total: number;
    readonly transactions_succeeded: number;
    readonly transactions_failed: number;
    readonly created: number;
    readonly updated: number;
    readonly status: string;
    readonly errors: Array<string>;
    published?: boolean;
};

export type ListCreateTransactionBatchResponse = {
    status?: string;
    data?: ListCreateTransactionBatch;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListTransaction = {
    readonly id: number;
    readonly updated: string;
    readonly created: string;
    amount?: string | null;
    currency?: string | null;
    user?: string | null;
    recipient?: string | null;
    credit_account?: string | null;
    credit_metadata?: {
        [key: string]: unknown;
    } | null;
    credit_note?: string | null;
    credit_reference?: string | null;
    credit_subtype?: string | null;
    debit_account?: string | null;
    debit_metadata?: {
        [key: string]: unknown;
    } | null;
    debit_note?: string | null;
    debit_reference?: string | null;
    debit_subtype?: string | null;
    uploaded_to_rehive?: boolean;
    rehive_error?: string | null;
    processed?: boolean;
    idempotency_key?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListTransactionUpdateRow = {
    readonly id: number;
    readonly updated: string;
    readonly created: string;
    tx_id: string;
    note?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    uploaded_to_rehive?: boolean;
    rehive_error?: string | null;
    processed?: boolean;
    idempotency_key?: string | null;
};

export type PaginatedAdminListCreateTransactionBatchList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminListCreateTransactionBatch>;
};

export type PaginatedAdminListCreateTransactionBatchListResponse = {
    status?: string;
    data?: PaginatedAdminListCreateTransactionBatchList;
};

export type PaginatedAdminListCreateTransactionUpdateBatchList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminListCreateTransactionUpdateBatch>;
};

export type PaginatedAdminListCreateTransactionUpdateBatchListResponse = {
    status?: string;
    data?: PaginatedAdminListCreateTransactionUpdateBatchList;
};

export type PaginatedListCreateTransactionBatchList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListCreateTransactionBatch>;
};

export type PaginatedListCreateTransactionBatchListResponse = {
    status?: string;
    data?: PaginatedListCreateTransactionBatchList;
};

export type PaginatedListTransactionList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListTransaction>;
};

export type PaginatedListTransactionListResponse = {
    status?: string;
    data?: PaginatedListTransactionList;
};

export type PaginatedListTransactionUpdateRowList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListTransactionUpdateRow>;
};

export type PaginatedListTransactionUpdateRowListResponse = {
    status?: string;
    data?: PaginatedListTransactionUpdateRowList;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompany = {
    readonly id?: string;
    readonly secret?: string;
    name?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionBatch = {
    readonly id?: string;
    readonly file?: string;
    readonly file_hash?: string | null;
    readonly transactions_total?: number;
    readonly transactions_succeeded?: number;
    readonly transactions_failed?: number;
    readonly created?: number;
    readonly updated?: number;
    readonly status?: string;
    readonly errors?: Array<string>;
    published?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionUpdateBatch = {
    readonly id?: string;
    readonly file?: string;
    readonly file_hash?: string | null;
    readonly rows_total?: number;
    readonly rows_succeeded?: number;
    readonly rows_failed?: number;
    readonly created?: number;
    readonly updated?: number;
    readonly status?: string;
    readonly errors?: Array<string>;
    published?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionBatch = {
    readonly id: string;
    readonly file: string;
    readonly file_hash: string | null;
    readonly transactions_total: number;
    readonly transactions_succeeded: number;
    readonly transactions_failed: number;
    readonly created: number;
    readonly updated: number;
    readonly status: string;
    readonly errors: Array<string>;
    published?: boolean;
};

export type TransactionBatchResponse = {
    status?: string;
    data?: TransactionBatch;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionUpdateBatch = {
    readonly id: string;
    readonly file: string;
    readonly file_hash: string | null;
    readonly rows_total: number;
    readonly rows_succeeded: number;
    readonly rows_failed: number;
    readonly created: number;
    readonly updated: number;
    readonly status: string;
    readonly errors: Array<string>;
    published?: boolean;
};

export type Webhook = {
    id: string;
    /**
     * * `currency.create` - currency.create
     * * `currency.update` - currency.update
     */
    event: 'currency.create' | 'currency.update';
    company: string;
    data: {
        [key: string]: unknown;
    };
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminCompanyWritable = {
    name?: string | null;
};

export type AdminCompanyResponseWritable = {
    status?: string;
    data?: AdminCompanyWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminListCreateTransactionBatchWritable = {
    file: string;
    published?: boolean;
    /**
     * * `admin` - Admin
     * * `user` - User
     */
    section: 'admin' | 'user';
};

export type AdminListCreateTransactionBatchResponseWritable = {
    status?: string;
    data?: AdminListCreateTransactionBatchWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type AdminListCreateTransactionUpdateBatchWritable = {
    file: string;
    published?: boolean;
    /**
     * * `admin` - Admin
     */
    section?: 'admin';
};

export type AdminListCreateTransactionUpdateBatchResponseWritable = {
    status?: string;
    data?: AdminListCreateTransactionUpdateBatchWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListCreateTransactionBatchWritable = {
    file: string;
    published?: boolean;
};

export type ListCreateTransactionBatchResponseWritable = {
    status?: string;
    data?: ListCreateTransactionBatchWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListTransactionWritable = {
    amount?: string | null;
    currency?: string | null;
    user?: string | null;
    recipient?: string | null;
    credit_account?: string | null;
    credit_metadata?: {
        [key: string]: unknown;
    } | null;
    credit_note?: string | null;
    credit_reference?: string | null;
    credit_subtype?: string | null;
    debit_account?: string | null;
    debit_metadata?: {
        [key: string]: unknown;
    } | null;
    debit_note?: string | null;
    debit_reference?: string | null;
    debit_subtype?: string | null;
    uploaded_to_rehive?: boolean;
    rehive_error?: string | null;
    processed?: boolean;
    idempotency_key?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type ListTransactionUpdateRowWritable = {
    tx_id: string;
    note?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    uploaded_to_rehive?: boolean;
    rehive_error?: string | null;
    processed?: boolean;
    idempotency_key?: string | null;
};

export type PaginatedAdminListCreateTransactionBatchListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminListCreateTransactionBatchWritable>;
};

export type PaginatedAdminListCreateTransactionBatchListResponseWritable = {
    status?: string;
    data?: PaginatedAdminListCreateTransactionBatchListWritable;
};

export type PaginatedAdminListCreateTransactionUpdateBatchListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<AdminListCreateTransactionUpdateBatchWritable>;
};

export type PaginatedAdminListCreateTransactionUpdateBatchListResponseWritable = {
    status?: string;
    data?: PaginatedAdminListCreateTransactionUpdateBatchListWritable;
};

export type PaginatedListCreateTransactionBatchListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListCreateTransactionBatchWritable>;
};

export type PaginatedListCreateTransactionBatchListResponseWritable = {
    status?: string;
    data?: PaginatedListCreateTransactionBatchListWritable;
};

export type PaginatedListTransactionListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListTransactionWritable>;
};

export type PaginatedListTransactionListResponseWritable = {
    status?: string;
    data?: PaginatedListTransactionListWritable;
};

export type PaginatedListTransactionUpdateRowListWritable = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ListTransactionUpdateRowWritable>;
};

export type PaginatedListTransactionUpdateRowListResponseWritable = {
    status?: string;
    data?: PaginatedListTransactionUpdateRowListWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedAdminCompanyWritable = {
    name?: string | null;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionBatchWritable = {
    published?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type PatchedTransactionUpdateBatchWritable = {
    published?: boolean;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionBatchWritable = {
    published?: boolean;
};

export type TransactionBatchResponseWritable = {
    status?: string;
    data?: TransactionBatchWritable;
};

/**
 * A ModelSerializer that takes additional arguments for
 * "fields", "omit" and "expand" in order to
 * control which fields are displayed, and whether to replace simple
 * values with complex, nested serializations
 */
export type TransactionUpdateBatchWritable = {
    published?: boolean;
};

export type ActivateCreateData = {
    body: Activate;
    path?: never;
    query?: never;
    url: '/activate/';
};

export type ActivateCreateResponses = {
    200: ActionResponse;
};

export type ActivateCreateResponse = ActivateCreateResponses[keyof ActivateCreateResponses];

export type AdminCompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyRetrieveResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyRetrieveResponse = AdminCompanyRetrieveResponses[keyof AdminCompanyRetrieveResponses];

export type AdminCompanyPartialUpdateData = {
    body?: PatchedAdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyPartialUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyPartialUpdateResponse = AdminCompanyPartialUpdateResponses[keyof AdminCompanyPartialUpdateResponses];

export type AdminCompanyUpdateData = {
    body?: AdminCompanyWritable;
    path?: never;
    query?: never;
    url: '/admin/company/';
};

export type AdminCompanyUpdateResponses = {
    200: AdminCompanyResponse;
};

export type AdminCompanyUpdateResponse = AdminCompanyUpdateResponses[keyof AdminCompanyUpdateResponses];

export type AdminTransactionUpdateBatchesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        section?: string;
        user?: string;
    };
    url: '/admin/transaction-update-batches/';
};

export type AdminTransactionUpdateBatchesListResponses = {
    200: PaginatedAdminListCreateTransactionUpdateBatchListResponse;
};

export type AdminTransactionUpdateBatchesListResponse = AdminTransactionUpdateBatchesListResponses[keyof AdminTransactionUpdateBatchesListResponses];

export type AdminTransactionUpdateBatchesCreateData = {
    body: AdminListCreateTransactionUpdateBatchWritable;
    path?: never;
    query?: never;
    url: '/admin/transaction-update-batches/';
};

export type AdminTransactionUpdateBatchesCreateResponses = {
    201: AdminListCreateTransactionUpdateBatchResponse;
};

export type AdminTransactionUpdateBatchesCreateResponse = AdminTransactionUpdateBatchesCreateResponses[keyof AdminTransactionUpdateBatchesCreateResponses];

export type AdminTransactionUpdateBatchesRetrieveData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/transaction-update-batches/{batch_id}/';
};

export type AdminTransactionUpdateBatchesRetrieveResponses = {
    200: AdminListCreateTransactionUpdateBatchResponse;
};

export type AdminTransactionUpdateBatchesRetrieveResponse = AdminTransactionUpdateBatchesRetrieveResponses[keyof AdminTransactionUpdateBatchesRetrieveResponses];

export type AdminTransactionUpdateBatchesPartialUpdateData = {
    body?: PatchedTransactionUpdateBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/transaction-update-batches/{batch_id}/';
};

export type AdminTransactionUpdateBatchesPartialUpdateResponses = {
    200: AdminListCreateTransactionUpdateBatchResponse;
};

export type AdminTransactionUpdateBatchesPartialUpdateResponse = AdminTransactionUpdateBatchesPartialUpdateResponses[keyof AdminTransactionUpdateBatchesPartialUpdateResponses];

export type AdminTransactionUpdateBatchesUpdateData = {
    body?: TransactionUpdateBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/transaction-update-batches/{batch_id}/';
};

export type AdminTransactionUpdateBatchesUpdateResponses = {
    200: AdminListCreateTransactionUpdateBatchResponse;
};

export type AdminTransactionUpdateBatchesUpdateResponse = AdminTransactionUpdateBatchesUpdateResponses[keyof AdminTransactionUpdateBatchesUpdateResponses];

export type AdminTransactionUpdateBatchesRowsListData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/transaction-update-batches/{batch_id}/rows/';
};

export type AdminTransactionUpdateBatchesRowsListResponses = {
    200: PaginatedListTransactionUpdateRowListResponse;
};

export type AdminTransactionUpdateBatchesRowsListResponse = AdminTransactionUpdateBatchesRowsListResponses[keyof AdminTransactionUpdateBatchesRowsListResponses];

export type AdminUploadsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        section?: string;
        user?: string;
    };
    url: '/admin/uploads/';
};

export type AdminUploadsListResponses = {
    200: PaginatedAdminListCreateTransactionBatchListResponse;
};

export type AdminUploadsListResponse = AdminUploadsListResponses[keyof AdminUploadsListResponses];

export type AdminUploadsCreateData = {
    body: AdminListCreateTransactionBatchWritable;
    path?: never;
    query?: never;
    url: '/admin/uploads/';
};

export type AdminUploadsCreateResponses = {
    201: AdminListCreateTransactionBatchResponse;
};

export type AdminUploadsCreateResponse = AdminUploadsCreateResponses[keyof AdminUploadsCreateResponses];

export type AdminUploadsRetrieveData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/uploads/{batch_id}/';
};

export type AdminUploadsRetrieveResponses = {
    200: AdminListCreateTransactionBatchResponse;
};

export type AdminUploadsRetrieveResponse = AdminUploadsRetrieveResponses[keyof AdminUploadsRetrieveResponses];

export type AdminUploadsPartialUpdateData = {
    body?: PatchedTransactionBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/uploads/{batch_id}/';
};

export type AdminUploadsPartialUpdateResponses = {
    200: AdminListCreateTransactionBatchResponse;
};

export type AdminUploadsPartialUpdateResponse = AdminUploadsPartialUpdateResponses[keyof AdminUploadsPartialUpdateResponses];

export type AdminUploadsUpdateData = {
    body?: TransactionBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/admin/uploads/{batch_id}/';
};

export type AdminUploadsUpdateResponses = {
    200: AdminListCreateTransactionBatchResponse;
};

export type AdminUploadsUpdateResponse = AdminUploadsUpdateResponses[keyof AdminUploadsUpdateResponses];

export type AdminUploadsTransactionsListData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/admin/uploads/{batch_id}/transactions/';
};

export type AdminUploadsTransactionsListResponses = {
    200: PaginatedListTransactionListResponse;
};

export type AdminUploadsTransactionsListResponse = AdminUploadsTransactionsListResponses[keyof AdminUploadsTransactionsListResponses];

export type DeactivateCreateData = {
    body: Deactivate;
    path?: never;
    query?: never;
    url: '/deactivate/';
};

export type DeactivateCreateResponses = {
    200: ActionResponse;
};

export type DeactivateCreateResponse = DeactivateCreateResponses[keyof DeactivateCreateResponses];

export type UploadsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/uploads/';
};

export type UploadsListResponses = {
    200: PaginatedListCreateTransactionBatchListResponse;
};

export type UploadsListResponse = UploadsListResponses[keyof UploadsListResponses];

export type UploadsCreateData = {
    body: ListCreateTransactionBatchWritable;
    path?: never;
    query?: never;
    url: '/uploads/';
};

export type UploadsCreateResponses = {
    201: ListCreateTransactionBatchResponse;
};

export type UploadsCreateResponse = UploadsCreateResponses[keyof UploadsCreateResponses];

export type UploadsRetrieveData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/uploads/{batch_id}/';
};

export type UploadsRetrieveResponses = {
    200: TransactionBatchResponse;
};

export type UploadsRetrieveResponse = UploadsRetrieveResponses[keyof UploadsRetrieveResponses];

export type UploadsPartialUpdateData = {
    body?: PatchedTransactionBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/uploads/{batch_id}/';
};

export type UploadsPartialUpdateResponses = {
    200: TransactionBatchResponse;
};

export type UploadsPartialUpdateResponse = UploadsPartialUpdateResponses[keyof UploadsPartialUpdateResponses];

export type UploadsUpdateData = {
    body?: TransactionBatchWritable;
    path: {
        batch_id: string;
    };
    query?: never;
    url: '/uploads/{batch_id}/';
};

export type UploadsUpdateResponses = {
    200: TransactionBatchResponse;
};

export type UploadsUpdateResponse = UploadsUpdateResponses[keyof UploadsUpdateResponses];

export type UploadsTransactionsListData = {
    body?: never;
    path: {
        batch_id: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/uploads/{batch_id}/transactions/';
};

export type UploadsTransactionsListResponses = {
    200: PaginatedListTransactionListResponse;
};

export type UploadsTransactionsListResponse = UploadsTransactionsListResponses[keyof UploadsTransactionsListResponses];

export type WebhookCreateData = {
    body: Webhook;
    path?: never;
    query?: never;
    url: '/webhook/';
};

export type WebhookCreateResponses = {
    200: ActionResponse;
};

export type WebhookCreateResponse = WebhookCreateResponses[keyof WebhookCreateResponses];
